# Debug only: Make sure pod can be visited from controller that deployed in mac.
apiVersion: v1
kind: Service
metadata:
  name: vllm-llama3-8b-instruct
  namespace: default
  labels:
    prometheus-discovery: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8000"
spec:
  selector:
    model.aibrix.ai/name: "vllm-llama3-8b-instruct"
  ports:
    - protocol: TCP
      name: inference
      port: 8010
      targetPort: 8010
      nodePort: 30082
  type: NodePort
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vllm-llama3-8b-instruct-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vllm-llama3-8b-instruct-reader-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vllm-llama3-8b-instruct-pod-reader-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: vllm-llama3-8b-instruct-sa
    namespace: default
roleRef:
  kind: Role
  name: vllm-llama3-8b-instruct-pod-reader-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: vllm-llama3-8b-instruct-deployment-reader-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vllm-llama3-8b-instruct-deployment-reader-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: vllm-llama3-8b-instruct-sa
    namespace: default
roleRef:
  kind: Role
  name: vllm-llama3-8b-instruct-deployment-reader-role
  apiGroup: rbac.authorization.k8s.io
