apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-autoscaler
  namespace: aibrix-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: aibrix-system
  name: deployment-reader
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-reader-binding
  namespace: aibrix-system
subjects:
  - kind: ServiceAccount
    name: pod-autoscaler
    namespace: aibrix-system
roleRef:
  kind: Role
  name: deployment-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-optimizer
  namespace: aibrix-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-optimizer
  template:
    metadata:
      labels:
        app: gpu-optimizer
    spec:
      serviceAccountName: pod-autoscaler
      automountServiceAccountToken: true # Important!
      containers:
      - name: gpu-optimizer
        image: aibrix/runtime:nightly
        command: ["python", "-m", "aibrix.gpu_optimizer.app", "--debug"]
        ports:
        - containerPort: 8080
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: REDIS_HOST
            value: aibrix-redis-master.aibrix-system.svc.cluster.local
---
# Debug only: Make sure pod can be visited from controller that deployed in mac.
apiVersion: v1
kind: Service
metadata:
  name: gpu-optimizer
  namespace: aibrix-system
spec:
  selector:
    app: gpu-optimizer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30008
  type: NodePort