apiVersion: v1
kind: Pod
metadata:
  name: disagg-proxy-router
spec:
  containers:
    - name: disagg-proxy
      image: kvcache-container-image-hb2-cn-beijing.cr.volces.com/aibrix/vllm-openai:v0.9.2-cu128-nixl-v0.4.1-lmcache-0.3.1.post1
      command: ["sh", "-c"]
      args:
        - |
          sleep 6000
