apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-facebook-opt-125m
spec:
  replicas: 3
  selector:
    matchLabels:
      adapter.model.aibrix.ai/enabled: "true"
      model.aibrix.ai/name: "facebook-opt-125m"
      app: "mock-facebook-opt-125m"
  template:
    spec:
      serviceAccountName: mocked-app-sa
      containers:
        - name: llm-engine
          image: aibrix/vllm-cpu-env:macos
          command: ["/bin/sh", "-c"]
          args: ["vllm serve facebook/opt-125m --trust-remote-code --enable-chunked-prefill --enable-prefix-caching --max_num_batched_tokens 1024"]
          volumeMounts:
          - name: model
            mountPath: /root/.cache/huggingface
      volumes:
      - name: model
        hostPath:
          path: /root/.cache/huggingface