apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-facebook-opt-125m
spec:
  replicas: 1
  selector:
    matchLabels:
      adapter.model.aibrix.ai/enabled: "true"
      model.aibrix.ai/name: "facebook-opt-125m"
      app: "mock-facebook-opt-125m"
  template:
    spec:
      serviceAccountName: mocked-app-sa
      containers:
        - name: llm-engine
          image: aibrix/vllm-cpu-env:macos
          command: ["/bin/sh", "-c"]
          args: ["vllm serve facebook/opt-125m --served-model-name facebook-opt-125m --chat-template /etc/chat-template-config/chat-template.j2 --trust-remote-code --device cpu --disable_async_output_proc --enforce-eager --dtype float16"]
          volumeMounts:
          - name: model
            mountPath: /root/.cache/huggingface
          - name: chat-template-volume
            mountPath: /etc/chat-template-config
      volumes:
      - name: model
        hostPath:
          path: /root/.cache/huggingface
      - name: chat-template-volume
        configMap:
          name: chat-template-config
          