apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-llama2-7b
  labels:
    model.aibrix.ai/name: "llama2-7b"
    model.aibrix.ai/port: "8000"
    adapter.model.aibrix.ai/enabled: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      adapter.model.aibrix.ai/enabled: "true"
      model.aibrix.ai/name: "llama2-7b"
      app: "mock-llama2-7b"
  template:
    metadata:
      labels:
        adapter.model.aibrix.ai/enabled: "true"
        model.aibrix.ai/name: "llama2-7b"
        app: "mock-llama2-7b"
    spec:
      serviceAccountName: mocked-app-sa
      containers:
        - name: llm-engine
          image: aibrix/vllm-mock:nightly
          command:
            - python3
            - app.py
            - --api_key
            - test-key-1234567890