apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama2-70b
  namespace: default
  labels:
    aibricks.com/lora-enabled: "true"
    model.aibrix.ai: "llama2-70b"
    model.aibrix.ai/port: "8000"
spec:
  replicas: 1
  selector:
    matchLabels:
      aibricks.com/lora-enabled: "true"
      model.aibrix.ai: "llama2-70b"
  template:
    metadata:
      labels:
        aibricks.com/lora-enabled: "true"
        model.aibrix.ai: "llama2-70b"
    spec:
      containers:
        - name: llmengine
          image: aibrix/vllm:v0.1.0
          ports:
            - containerPort: 8000
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

---
# Debug only: Make sure pod can be visited from controller that deployed in mac.
apiVersion: v1
kind: Service
metadata:
  name: llama2-70b
  namespace: default
spec:
  selector:
    model.aibrix.ai: "llama2-70b"
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
  type: NodePort

# ---
# for test-purpose, if need to create HTTPRoute object manually
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: llama2-70b-router
# spec:
#   parentRefs:
#     - name: eg
#   rules:
#     - matches:
#         - headers:
#             - type: Exact
#               name: model
#               value: llama2-70b
#       backendRefs:
#         - name: llama2-70b
#           port: 8000
