apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama2-70b
  namespace: aibrix-system
  labels:
    aibricks.com/lora-enabled: "true"
    model.aibrix.ai: "llama2-70b"
    model.aibrix.ai/port: "8000"
spec:
  replicas: 3
  selector:
    matchLabels:
      aibricks.com/lora-enabled: "true"
      model.aibrix.ai: "llama2-70b"
  template:
    metadata:
      labels:
        aibricks.com/lora-enabled: "true"
        model.aibrix.ai: "llama2-70b"
    spec:
      containers:
        - name: llmengine
          image: aibrix/vllm:v0.1.0
          ports:
            - containerPort: 8000
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
---
# Debug only: Make sure pod can be visited from controller that deployed in mac.
apiVersion: v1
kind: Service
metadata:
  name: llama2-70b
  namespace: aibrix-system
spec:
  selector:
    model.aibrix.ai: "llama2-70b"
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080
  type: NodePort
# ---
# for test-purpose, if need to create HTTPRoute object manually
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: llama2-70b-router
# spec:
#   parentRefs:
#     - name: eg
#   rules:
#     - matches:
#         - headers:
#             - type: Exact
#               name: model
#               value: llama2-70b
#       backendRefs:
#         - name: llama2-70b
#           port: 8000
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: aibrix-system
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: aibrix-system
subjects:
- kind: ServiceAccount
  name: default
  namespace: aibrix-system
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: deployment-reader
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-reader-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: deployment-reader
  apiGroup: rbac.authorization.k8s.io