apiVersion: v1
kind: Service
metadata:
  name: aibrix-gateway-plugins
  namespace: aibrix-system
spec:
  selector:
    app: gateway-plugins
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aibrix-gateway-plugins
  namespace: aibrix-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-plugins
  template:
    metadata:
      labels:
        app: gateway-plugins
    spec:
      serviceAccountName: aibrix-gateway-plugin
      initContainers:
        - name: init-c
          image: busybox
          command: ['sh', '-c', "until nslookup aibrix-redis-master.aibrix-system.svc.cluster.local; do echo waiting for service aibrix-redis-master; sleep 2; done"]
      containers:
        - name: golang-app-container
          image: aibrix/plugins:nightly
          ports:
            - containerPort: 50052
          env:
            - name: REDIS_HOST
              value: aibrix-redis-master
            - name: REDIS_PORT
              value: "6379" 
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace

