# Patch for k8s_job_template.yaml to enable S3 testing with Kubernetes secrets
apiVersion: batch/v1
kind: Job
spec:
  template:
    spec:
      containers:
      - name: batch-worker
        env:
        - name: STORAGE_TOS_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aibrix-tos-credentials
              key: access-key
        - name: STORAGE_TOS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: aibrix-tos-credentials
              key: secret-key
        - name: STORAGE_TOS_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: aibrix-tos-credentials
              key: endpoint
        - name: STORAGE_TOS_REGION
          valueFrom:
            secretKeyRef:
              name: aibrix-tos-credentials
              key: region
        - name: STORAGE_TOS_BUCKET
          valueFrom:
            secretKeyRef:
              name: aibrix-tos-credentials
              key: bucket-name