apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-reader-sa
  namespace: default
---
# Service Account for job pod
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-reader-role
  namespace: default
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get"] # Get permissions only
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-reader-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: job-reader-sa
  namespace: default
roleRef:
  kind: Role
  name: job-reader-role
  apiGroup: rbac.authorization.k8s.io