apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job-template
  namespace: default
  labels:
    app: aibrix-batch
    component: batch-processor
  annotations:
    # Template annotations will be merged with BatchJobSpec annotations
spec:
  template:
    metadata:
      labels:
        app: aibrix-batch
        component: batch-processor
    spec:
      restartPolicy: Never
      containers:
      - name: batch-processor
        image: batch-processor:latest
        env:
        - name: INPUT_FILE_ID
          value: ""  # Will be filled from BatchJobSpec
        - name: ENDPOINT
          value: ""  # Will be filled from BatchJobSpec
        - name: COMPLETION_WINDOW
          value: ""  # Will be filled from BatchJobSpec
  backoffLimit: 3
  activeDeadlineSeconds: 86400  # 24 hours