apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulator-llama2-7b
  namespace: aibrix-system
  labels:
    modeladapter.aibricks.ai/enabled: "true"
    model.aibrix.ai: "llama2-7b"
    model.aibrix.ai/port: "8000"
spec:
  replicas: 1
  selector:
    matchLabels:
      modeladapter.aibricks.ai/enabled: "true"
      model.aibrix.ai: "llama2-7b"
  template:
    metadata:
      labels:
        modeladapter.aibricks.ai/enabled: "true"
        model.aibrix.ai: "llama2-7b"
    spec:
      containers:
        - name: llmengine-simulator
          image: aibrix/vllm-simulator:nightly
          ports:
            - containerPort: 8000
          env:
            - name: DEPLOYMENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MODEL_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['model.aibrix.ai']

# ---
# Debug only: Make sure pod can be visited from controller that deployed in mac.
apiVersion: v1
kind: Service
metadata:
  name: llama2-7b
  namespace: aibrix-system
spec:
  selector:
    model.aibrix.ai: "llama2-7b"
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30081
  type: NodePort
# ---
# for test-purpose, if need to create HTTPRoute object manually
# apiVersion: gateway.networking.k8s.io/v1
# kind: HTTPRoute
# metadata:
#   name: llama2-7b-router
#   namespace: aibrix-system
# spec:
#   parentRefs:
#     - name: aibrix-eg
#   rules:
#     - matches:
#         - headers:
#             - type: Exact
#               name: model
#               value: llama2-7b
#       backendRefs:
#         - name: llama2-7b
#           port: 8000