name: simulator
channels:
  - conda-forge
  - plotly
dependencies:
  - python>=3.10
  - setuptools
  - pip
  - numpy
  - plotly_express
  - jupyterlab
  - matplotlib
  - pyyaml
  - snakeviz
  - scikit-learn
  - python-kaleido
  - wandb
  - fasteners
  - ray-all
  - streamlit
  - randomname
  - flask
  - kubernetes
  - transformers
  - pip:
    - kaleido
    - ddsketch
    - paretoset
    - git+https://github.com/zhangjyr/vidur.git