apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway-plugin-metrics-monitor
  namespace: aibrix-system
  labels:
    release: prometheus
    app.kubernetes.io/component: aibrix-gateway-plugin
    app.kubernetes.io/name: aibrix
spec:
  selector:
    matchLabels:
      app: gateway-plugins
  endpoints:
  - port: metrics
    path: /metrics
    interval: 15s
    honorLabels: true
  namespaceSelector:
    matchNames:
    - aibrix-system
