namespace: aibrix-system

namePrefix: aibrix-

resources:
- ../../../crd
- ../../../rbac
- manager
- gateway
- gpu-optimizer
- ../../../dependency/kuberay-operator


images:
- name: quay.io/kuberay/operator
  newName: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/kuberay-operator
  newTag: v1.2.1-patch