/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// ModelWarmupCustomActionApplyConfiguration represents a declarative configuration of the ModelWarmupCustomAction type for use
// with apply.
type ModelWarmupCustomActionApplyConfiguration struct {
	InitContainers   []v1.Container            `json:"initContainers,omitempty"`
	Containers       []v1.Container            `json:"containers,omitempty"`
	Volumes          []v1.Volume               `json:"volumes,omitempty"`
	ImagePullSecrets []v1.LocalObjectReference `json:"imagePullSecrets,omitempty"`
}

// ModelWarmupCustomActionApplyConfiguration constructs a declarative configuration of the ModelWarmupCustomAction type for use with
// apply.
func ModelWarmupCustomAction() *ModelWarmupCustomActionApplyConfiguration {
	return &ModelWarmupCustomActionApplyConfiguration{}
}

// WithInitContainers adds the given value to the InitContainers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the InitContainers field.
func (b *ModelWarmupCustomActionApplyConfiguration) WithInitContainers(values ...v1.Container) *ModelWarmupCustomActionApplyConfiguration {
	for i := range values {
		b.InitContainers = append(b.InitContainers, values[i])
	}
	return b
}

// WithContainers adds the given value to the Containers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Containers field.
func (b *ModelWarmupCustomActionApplyConfiguration) WithContainers(values ...v1.Container) *ModelWarmupCustomActionApplyConfiguration {
	for i := range values {
		b.Containers = append(b.Containers, values[i])
	}
	return b
}

// WithVolumes adds the given value to the Volumes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Volumes field.
func (b *ModelWarmupCustomActionApplyConfiguration) WithVolumes(values ...v1.Volume) *ModelWarmupCustomActionApplyConfiguration {
	for i := range values {
		b.Volumes = append(b.Volumes, values[i])
	}
	return b
}

// WithImagePullSecrets adds the given value to the ImagePullSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the ImagePullSecrets field.
func (b *ModelWarmupCustomActionApplyConfiguration) WithImagePullSecrets(values ...v1.LocalObjectReference) *ModelWarmupCustomActionApplyConfiguration {
	for i := range values {
		b.ImagePullSecrets = append(b.ImagePullSecrets, values[i])
	}
	return b
}
