/*
Copyright 2026 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vllm-project/aibrix/api/model/v1alpha1"
)

// ModelClaimInstanceApplyConfiguration represents a declarative configuration of the ModelClaimInstance type for use
// with apply.
type ModelClaimInstanceApplyConfiguration struct {
	Pod   *string                   `json:"pod,omitempty"`
	Port  *int32                    `json:"port,omitempty"`
	Phase *v1alpha1.ModelClaimPhase `json:"phase,omitempty"`
}

// ModelClaimInstanceApplyConfiguration constructs a declarative configuration of the ModelClaimInstance type for use with
// apply.
func ModelClaimInstance() *ModelClaimInstanceApplyConfiguration {
	return &ModelClaimInstanceApplyConfiguration{}
}

// WithPod sets the Pod field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Pod field is set to the value of the last call.
func (b *ModelClaimInstanceApplyConfiguration) WithPod(value string) *ModelClaimInstanceApplyConfiguration {
	b.Pod = &value
	return b
}

// WithPort sets the Port field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Port field is set to the value of the last call.
func (b *ModelClaimInstanceApplyConfiguration) WithPort(value int32) *ModelClaimInstanceApplyConfiguration {
	b.Port = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *ModelClaimInstanceApplyConfiguration) WithPhase(value v1alpha1.ModelClaimPhase) *ModelClaimInstanceApplyConfiguration {
	b.Phase = &value
	return b
}
