/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ModelWarmupPoliciesApplyConfiguration represents a declarative configuration of the ModelWarmupPolicies type for use
// with apply.
type ModelWarmupPoliciesApplyConfiguration struct {
	Parallelism             *int32 `json:"parallelism,omitempty"`
	GlobalTimeoutSeconds    *int64 `json:"globalTimeoutSeconds,omitempty"`
	RetryLimit              *int32 `json:"retryLimit,omitempty"`
	TTLSecondsAfterFinished *int32 `json:"ttlSecondsAfterFinished,omitempty"`
}

// ModelWarmupPoliciesApplyConfiguration constructs a declarative configuration of the ModelWarmupPolicies type for use with
// apply.
func ModelWarmupPolicies() *ModelWarmupPoliciesApplyConfiguration {
	return &ModelWarmupPoliciesApplyConfiguration{}
}

// WithParallelism sets the Parallelism field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Parallelism field is set to the value of the last call.
func (b *ModelWarmupPoliciesApplyConfiguration) WithParallelism(value int32) *ModelWarmupPoliciesApplyConfiguration {
	b.Parallelism = &value
	return b
}

// WithGlobalTimeoutSeconds sets the GlobalTimeoutSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GlobalTimeoutSeconds field is set to the value of the last call.
func (b *ModelWarmupPoliciesApplyConfiguration) WithGlobalTimeoutSeconds(value int64) *ModelWarmupPoliciesApplyConfiguration {
	b.GlobalTimeoutSeconds = &value
	return b
}

// WithRetryLimit sets the RetryLimit field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RetryLimit field is set to the value of the last call.
func (b *ModelWarmupPoliciesApplyConfiguration) WithRetryLimit(value int32) *ModelWarmupPoliciesApplyConfiguration {
	b.RetryLimit = &value
	return b
}

// WithTTLSecondsAfterFinished sets the TTLSecondsAfterFinished field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TTLSecondsAfterFinished field is set to the value of the last call.
func (b *ModelWarmupPoliciesApplyConfiguration) WithTTLSecondsAfterFinished(value int32) *ModelWarmupPoliciesApplyConfiguration {
	b.TTLSecondsAfterFinished = &value
	return b
}
