/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// ModelWarmupNodesTargetApplyConfiguration represents a declarative configuration of the ModelWarmupNodesTarget type for use
// with apply.
type ModelWarmupNodesTargetApplyConfiguration struct {
	Names []string `json:"names,omitempty"`
}

// ModelWarmupNodesTargetApplyConfiguration constructs a declarative configuration of the ModelWarmupNodesTarget type for use with
// apply.
func ModelWarmupNodesTarget() *ModelWarmupNodesTargetApplyConfiguration {
	return &ModelWarmupNodesTargetApplyConfiguration{}
}

// WithNames adds the given value to the Names field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Names field.
func (b *ModelWarmupNodesTargetApplyConfiguration) WithNames(values ...string) *ModelWarmupNodesTargetApplyConfiguration {
	for i := range values {
		b.Names = append(b.Names, values[i])
	}
	return b
}
