/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vllm-project/aibrix/api/model/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ModelWarmupStatusApplyConfiguration represents a declarative configuration of the ModelWarmupStatus type for use
// with apply.
type ModelWarmupStatusApplyConfiguration struct {
	Phase            *v1alpha1.ModelWarmupPhase                  `json:"phase,omitempty"`
	ObservedRevision *string                                     `json:"observedRevision,omitempty"`
	DesiredNodes     *int32                                      `json:"desiredNodes,omitempty"`
	ActiveNodes      *int32                                      `json:"activeNodes,omitempty"`
	SucceededNodes   *int32                                      `json:"succeededNodes,omitempty"`
	FailedNodes      *int32                                      `json:"failedNodes,omitempty"`
	StartTime        *v1.Time                                    `json:"startTime,omitempty"`
	CompletionTime   *v1.Time                                    `json:"completionTime,omitempty"`
	Targets          []ModelWarmupTargetStatusApplyConfiguration `json:"targets,omitempty"`
	Conditions       []metav1.ConditionApplyConfiguration        `json:"conditions,omitempty"`
}

// ModelWarmupStatusApplyConfiguration constructs a declarative configuration of the ModelWarmupStatus type for use with
// apply.
func ModelWarmupStatus() *ModelWarmupStatusApplyConfiguration {
	return &ModelWarmupStatusApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *ModelWarmupStatusApplyConfiguration) WithPhase(value v1alpha1.ModelWarmupPhase) *ModelWarmupStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithObservedRevision sets the ObservedRevision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedRevision field is set to the value of the last call.
func (b *ModelWarmupStatusApplyConfiguration) WithObservedRevision(value string) *ModelWarmupStatusApplyConfiguration {
	b.ObservedRevision = &value
	return b
}

// WithDesiredNodes sets the DesiredNodes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DesiredNodes field is set to the value of the last call.
func (b *ModelWarmupStatusApplyConfiguration) WithDesiredNodes(value int32) *ModelWarmupStatusApplyConfiguration {
	b.DesiredNodes = &value
	return b
}

// WithActiveNodes sets the ActiveNodes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ActiveNodes field is set to the value of the last call.
func (b *ModelWarmupStatusApplyConfiguration) WithActiveNodes(value int32) *ModelWarmupStatusApplyConfiguration {
	b.ActiveNodes = &value
	return b
}

// WithSucceededNodes sets the SucceededNodes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SucceededNodes field is set to the value of the last call.
func (b *ModelWarmupStatusApplyConfiguration) WithSucceededNodes(value int32) *ModelWarmupStatusApplyConfiguration {
	b.SucceededNodes = &value
	return b
}

// WithFailedNodes sets the FailedNodes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailedNodes field is set to the value of the last call.
func (b *ModelWarmupStatusApplyConfiguration) WithFailedNodes(value int32) *ModelWarmupStatusApplyConfiguration {
	b.FailedNodes = &value
	return b
}

// WithStartTime sets the StartTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartTime field is set to the value of the last call.
func (b *ModelWarmupStatusApplyConfiguration) WithStartTime(value v1.Time) *ModelWarmupStatusApplyConfiguration {
	b.StartTime = &value
	return b
}

// WithCompletionTime sets the CompletionTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CompletionTime field is set to the value of the last call.
func (b *ModelWarmupStatusApplyConfiguration) WithCompletionTime(value v1.Time) *ModelWarmupStatusApplyConfiguration {
	b.CompletionTime = &value
	return b
}

// WithTargets adds the given value to the Targets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Targets field.
func (b *ModelWarmupStatusApplyConfiguration) WithTargets(values ...*ModelWarmupTargetStatusApplyConfiguration) *ModelWarmupStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithTargets")
		}
		b.Targets = append(b.Targets, *values[i])
	}
	return b
}

// WithConditions adds the given value to the Conditions field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Conditions field.
func (b *ModelWarmupStatusApplyConfiguration) WithConditions(values ...*metav1.ConditionApplyConfiguration) *ModelWarmupStatusApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithConditions")
		}
		b.Conditions = append(b.Conditions, *values[i])
	}
	return b
}
