/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// ModelWarmupImagePreloadApplyConfiguration represents a declarative configuration of the ModelWarmupImagePreload type for use
// with apply.
type ModelWarmupImagePreloadApplyConfiguration struct {
	Images      []ModelWarmupImageApplyConfiguration `json:"images,omitempty"`
	PullSecrets []v1.LocalObjectReference            `json:"pullSecrets,omitempty"`
}

// ModelWarmupImagePreloadApplyConfiguration constructs a declarative configuration of the ModelWarmupImagePreload type for use with
// apply.
func ModelWarmupImagePreload() *ModelWarmupImagePreloadApplyConfiguration {
	return &ModelWarmupImagePreloadApplyConfiguration{}
}

// WithImages adds the given value to the Images field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Images field.
func (b *ModelWarmupImagePreloadApplyConfiguration) WithImages(values ...*ModelWarmupImageApplyConfiguration) *ModelWarmupImagePreloadApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithImages")
		}
		b.Images = append(b.Images, *values[i])
	}
	return b
}

// WithPullSecrets adds the given value to the PullSecrets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the PullSecrets field.
func (b *ModelWarmupImagePreloadApplyConfiguration) WithPullSecrets(values ...v1.LocalObjectReference) *ModelWarmupImagePreloadApplyConfiguration {
	for i := range values {
		b.PullSecrets = append(b.PullSecrets, values[i])
	}
	return b
}
