/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ModelClaimSpecApplyConfiguration represents a declarative configuration of the ModelClaimSpec type for use
// with apply.
type ModelClaimSpecApplyConfiguration struct {
	ModelName    *string                                   `json:"modelName,omitempty"`
	PodSelector  *v1.LabelSelectorApplyConfiguration       `json:"podSelector,omitempty"`
	ArtifactURL  *string                                   `json:"artifactURL,omitempty"`
	Engine       *string                                   `json:"engine,omitempty"`
	Replicas     *int32                                    `json:"replicas,omitempty"`
	EngineConfig *ModelClaimEngineConfigApplyConfiguration `json:"engineConfig,omitempty"`
}

// ModelClaimSpecApplyConfiguration constructs a declarative configuration of the ModelClaimSpec type for use with
// apply.
func ModelClaimSpec() *ModelClaimSpecApplyConfiguration {
	return &ModelClaimSpecApplyConfiguration{}
}

// WithModelName sets the ModelName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ModelName field is set to the value of the last call.
func (b *ModelClaimSpecApplyConfiguration) WithModelName(value string) *ModelClaimSpecApplyConfiguration {
	b.ModelName = &value
	return b
}

// WithPodSelector sets the PodSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PodSelector field is set to the value of the last call.
func (b *ModelClaimSpecApplyConfiguration) WithPodSelector(value *v1.LabelSelectorApplyConfiguration) *ModelClaimSpecApplyConfiguration {
	b.PodSelector = value
	return b
}

// WithArtifactURL sets the ArtifactURL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ArtifactURL field is set to the value of the last call.
func (b *ModelClaimSpecApplyConfiguration) WithArtifactURL(value string) *ModelClaimSpecApplyConfiguration {
	b.ArtifactURL = &value
	return b
}

// WithEngine sets the Engine field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Engine field is set to the value of the last call.
func (b *ModelClaimSpecApplyConfiguration) WithEngine(value string) *ModelClaimSpecApplyConfiguration {
	b.Engine = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *ModelClaimSpecApplyConfiguration) WithReplicas(value int32) *ModelClaimSpecApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithEngineConfig sets the EngineConfig field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EngineConfig field is set to the value of the last call.
func (b *ModelClaimSpecApplyConfiguration) WithEngineConfig(value *ModelClaimEngineConfigApplyConfiguration) *ModelClaimSpecApplyConfiguration {
	b.EngineConfig = value
	return b
}
