/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vllm-project/aibrix/api/model/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ModelWarmupTargetStatusApplyConfiguration represents a declarative configuration of the ModelWarmupTargetStatus type for use
// with apply.
type ModelWarmupTargetStatusApplyConfiguration struct {
	NodeName           *string                          `json:"nodeName,omitempty"`
	Source             *string                          `json:"source,omitempty"`
	SourceCount        *int32                           `json:"sourceCount,omitempty"`
	Revision           *string                          `json:"revision,omitempty"`
	JobName            *string                          `json:"jobName,omitempty"`
	Phase              *v1alpha1.ModelWarmupTargetPhase `json:"phase,omitempty"`
	Reason             *string                          `json:"reason,omitempty"`
	Message            *string                          `json:"message,omitempty"`
	LastTransitionTime *v1.Time                         `json:"lastTransitionTime,omitempty"`
}

// ModelWarmupTargetStatusApplyConfiguration constructs a declarative configuration of the ModelWarmupTargetStatus type for use with
// apply.
func ModelWarmupTargetStatus() *ModelWarmupTargetStatusApplyConfiguration {
	return &ModelWarmupTargetStatusApplyConfiguration{}
}

// WithNodeName sets the NodeName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NodeName field is set to the value of the last call.
func (b *ModelWarmupTargetStatusApplyConfiguration) WithNodeName(value string) *ModelWarmupTargetStatusApplyConfiguration {
	b.NodeName = &value
	return b
}

// WithSource sets the Source field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Source field is set to the value of the last call.
func (b *ModelWarmupTargetStatusApplyConfiguration) WithSource(value string) *ModelWarmupTargetStatusApplyConfiguration {
	b.Source = &value
	return b
}

// WithSourceCount sets the SourceCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SourceCount field is set to the value of the last call.
func (b *ModelWarmupTargetStatusApplyConfiguration) WithSourceCount(value int32) *ModelWarmupTargetStatusApplyConfiguration {
	b.SourceCount = &value
	return b
}

// WithRevision sets the Revision field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Revision field is set to the value of the last call.
func (b *ModelWarmupTargetStatusApplyConfiguration) WithRevision(value string) *ModelWarmupTargetStatusApplyConfiguration {
	b.Revision = &value
	return b
}

// WithJobName sets the JobName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the JobName field is set to the value of the last call.
func (b *ModelWarmupTargetStatusApplyConfiguration) WithJobName(value string) *ModelWarmupTargetStatusApplyConfiguration {
	b.JobName = &value
	return b
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *ModelWarmupTargetStatusApplyConfiguration) WithPhase(value v1alpha1.ModelWarmupTargetPhase) *ModelWarmupTargetStatusApplyConfiguration {
	b.Phase = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *ModelWarmupTargetStatusApplyConfiguration) WithReason(value string) *ModelWarmupTargetStatusApplyConfiguration {
	b.Reason = &value
	return b
}

// WithMessage sets the Message field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Message field is set to the value of the last call.
func (b *ModelWarmupTargetStatusApplyConfiguration) WithMessage(value string) *ModelWarmupTargetStatusApplyConfiguration {
	b.Message = &value
	return b
}

// WithLastTransitionTime sets the LastTransitionTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastTransitionTime field is set to the value of the last call.
func (b *ModelWarmupTargetStatusApplyConfiguration) WithLastTransitionTime(value v1.Time) *ModelWarmupTargetStatusApplyConfiguration {
	b.LastTransitionTime = &value
	return b
}
