---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - autoscaling.aibrix.ai
  resources:
  - podautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling.aibrix.ai
  resources:
  - podautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - autoscaling.aibrix.ai
  resources:
  - podautoscalers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - model.aibrix.ai
  resources:
  - modeladapters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - model.aibrix.ai
  resources:
  - modeladapters/finalizers
  verbs:
  - update
- apiGroups:
  - model.aibrix.ai
  resources:
  - modeladapters/status
  verbs:
  - get
  - patch
  - update
