apiVersion: orchestration.aibrix.ai/v1alpha1
kind: StormService
metadata:
  name: replica-fix-xpyd
spec:
  replicas: 2
  updateStrategy:
    type: InPlaceUpdate
  stateful: true
  selector:
    matchLabels:
      app: replica-fix-xpyd
  template:
    metadata:
      labels:
        app: replica-fix-xpyd
    spec:
      roles:
        - name: prefill
          replicas: 2
          stateful: true
          template:
            metadata:
              annotations:
                k8s.volcengine.com/pod-networks: |
                  [
                    {
                      "cniConf":{
                          "name":"rdma"
                      }
                    }
                  ]
            spec:
              nodeSelector:
                kubernetes.io/hostname: 192.168.0.140
              containers:
                - name: prefill
                  image: iaas-gpu-cn-beijing.cr.volces.com/serving/sglang:v0.4.9.post2.iaas.dev.202507161949
                  command: ["sh", "-c"]
                  args:
                    - |
                      python3 -m sglang.launch_server \
                        --model-path /models/Qwen2.5-7B-Instruct \
                        --host 0.0.0.0 \
                        --port 30000 \
                        --disaggregation-mode prefill \
                        --trust-remote-code \
                        --mem-fraction-static 0.8 \
                        --log-level debug
                  env:
                    - name: GLOO_SOCKET_IFNAME
                      value: eth0
                    - name: NCCL_SOCKET_IFNAME
                      value: eth0
                    - name: NCCL_IB_DISABLE
                      value: "0"
                    - name: NCCL_IB_GID_INDEX
                      value: "7"
                    - name: NCCL_DEBUG
                      value: "INFO"
                  volumeMounts:
                    - name: model-vol
                      mountPath: /models
                    - mountPath: /dev/shm
                      name: shared-mem
                  resources:
                    limits:
                      nvidia.com/gpu: 1
                      vke.volcengine.com/rdma: "1"
                  securityContext:
                    capabilities:
                      add:
                        - IPC_LOCK
              volumes:
                - name: model-vol
                  hostPath:
                    path: /root/models
                    type: Directory
                - emptyDir:
                    medium: Memory
                  name: shared-mem
        - name: decode
          replicas: 1
          stateful: true
          template:
            metadata:
              annotations:
                k8s.volcengine.com/pod-networks: |
                  [
                    {
                      "cniConf":{
                          "name":"rdma"
                      }
                    }
                  ]
            spec:
              nodeSelector:
                kubernetes.io/hostname: 192.168.0.140
              containers:
                - name: decode
                  image: iaas-gpu-cn-beijing.cr.volces.com/serving/sglang:v0.4.9.post2.iaas.dev.202507161949
                  command: ["sh", "-c"]
                  args:
                    - |
                      python3 -m sglang.launch_server \
                        --model-path /models/Qwen2.5-7B-Instruct \
                        --host 0.0.0.0 \
                        --port 30000 \
                        --disaggregation-mode decode \
                        --trust-remote-code \
                        --mem-fraction-static 0.8 \
                        --log-level debug
                  env:
                    - name: GLOO_SOCKET_IFNAME
                      value: eth0
                    - name: NCCL_SOCKET_IFNAME
                      value: eth0
                    - name: NCCL_IB_DISABLE
                      value: "0"
                    - name: NCCL_IB_GID_INDEX
                      value: "7"
                    - name: NCCL_DEBUG
                      value: "INFO"
                  volumeMounts:
                    - name: model-vol
                      mountPath: /models
                    - mountPath: /dev/shm
                      name: shared-mem
                  resources:
                    limits:
                      nvidia.com/gpu: 1
                      vke.volcengine.com/rdma: "1"
                  securityContext:
                    capabilities:
                      add:
                        - IPC_LOCK
              volumes:
                - name: model-vol
                  hostPath:
                    path: /root/models
                    type: Directory
                - emptyDir:
                    medium: Memory
                  name: shared-mem

---

apiVersion: v1
kind: Pod
metadata:
  name: sglang-pd-sample-minilb
  labels:
    app: sglang-pd-sample
    role: lb
spec:
  restartPolicy: Never
  containers:
    - name: mini-lb
      image: kvcache-container-image-hb2-cn-beijing.cr.volces.com/aibrix/sglang-router:community_v0.4.9.post1-patch.2
      command: [ "sh", "-c" ]
      args:
        - |
          python3 -m sglang_router.launch_router \
            --pd-disaggregation \
            --policy random \
            --service-discovery \
            --service-discovery-port 30000 \
            --prefill-selector storm-service-name=replica-fix-xpyd role-name=prefill  \
            --decode-selector storm-service-name=replica-fix-xpyd role-name=decode \
            --service-discovery-namespace default
