name: 💬 Request for Comments (RFC)
description: Propose and discuss major architectural changes or design choices for AIBrix
title: "[RFC]: "
labels: ["RFC"]
body:
- type: markdown
  attributes:
    value: >
      #### Before submitting an RFC, please review previous RFCs for context and to avoid duplication.
- type: textarea
  attributes:
    label: Summary
    description: >
      Provide a brief overview of the proposed change or design decision.
  validations:
    required: true
- type: textarea
  attributes:
    label: Motivation
    description: >
      Explain the rationale behind this RFC. What problem does it solve? 
      How does it improve AIBrix's GenAI inference infrastructure?
  validations:
    required: true
- type: textarea
  attributes:
    label: Proposed Change
    description: >
      Describe the proposed change in detail. Include technical specifics, 
      potential implementation approaches, and how it integrates with existing AIBrix components.
  validations:
    required: true
- type: textarea
  attributes:
    label: Alternatives Considered
    description: >
      Discuss any alternative approaches you've considered and why they were not chosen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Impact and Risks
    description: >
      Evaluate the potential impact of this change on AIBrix's performance, scalability, and user experience. 
      Identify any risks or challenges in implementation.
  validations:
    required: true
- type: textarea
  attributes:
    label: Feedback Period
    description: >
      Specify the duration for which you're seeking feedback. Typically at least one week.
  validations:
    required: true
- type: textarea
  attributes:
    label: CC List
    description: >
      List any specific team members or stakeholders you'd like to involve in the discussion.
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional Context
    description: >
      Provide any additional information, context, or resources relevant to this RFC.
  validations:
    required: false
- type: markdown
  attributes:
    value: >
      Thank you for contributing to AIBrix's development! Your input helps shape the future of our GenAI inference infrastructure. 🎉