apiVersion: orchestration.aibrix.ai/v1alpha1
kind: KVCache
metadata:
  name: aibrix-deepseek-33b-kvcache
  namespace: aibrix-system
  annotations:
    kvcache.orchestration.aibrix.ai/node-affinity-gpu-type: NVIDIA-L20
    kvcache.orchestration.aibrix.ai/pod-affinity-workload: aibrix-deepseek-33b
spec:
  replicas: 1
  service:
    type: ClusterIP
    port: 9600
  cacheSpec:
    image: aibrix/kvcache:20241120
    imagePullPolicy: IfNotPresent
