apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: sd-3 
  labels: 
    model.aibrix.ai/name: sd-3 
    model.aibrix.ai/port: "6000" 
spec: 
  replicas: 1 
  strategy: 
    rollingUpdate: 
      maxSurge: 1 
      maxUnavailable: 1 
    type: RollingUpdate 
  selector: 
    matchLabels: 
      model.aibrix.ai/name: sd-3 
  template: 
    metadata: 
      labels: 
        model.aibrix.ai/name: sd-3 
        model.aibrix.ai/port: "6000" 
    spec: 
      containers: 
        - name: xdit-dev 
          image: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/xdit-dev:v0.28 #aibrix-cn-beijing.cr.volces.com/aibrix/vllm-openai:v0.8.5 
          imagePullPolicy: Always 
          command: ["sh", "-c"]
          args:
            - |
              sleep infinity
          env: []
          resources: 
            limits: 
              nvidia.com/gpu: "1" 
              cpu: "10" # memory: "150G" 
            requests: 
              nvidia.com/gpu: "1" 
              cpu: "10" # memory: "150G" 
          volumeMounts:
            - mountPath: /models 
              name: model-hostpath 
            - name: shared-data
              mountPath: /shared
        - name: aibrix-runtime
          image: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/runtime:v0.4.1-mm1
          command:
            - aibrix_runtime
            - --port
            - "8080"
          env:
            - name: INFERENCE_ENGINE
              value: vllm
            - name: INFERENCE_ENGINE_ENDPOINT
              value: http://localhost:8000
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: shared-data
              mountPath: /shared
      nodeSelector:
        kubernetes.io/hostname: 192.168.0.6
      volumes: 
        - name: model-hostpath 
          hostPath: 
            path: /data01/models
            type: Directory
        - name: shared-data
          emptyDir: {}  
--- 


apiVersion: v1 
kind: Service 
metadata: 
  labels: 
    model.aibrix.ai/name: sd-3 
    prometheus-discovery: "true" 
  annotations: 
    prometheus.io/scrape: "true" 
    prometheus.io/port: "8080" 
  name: sd-3 # Note: The Service name must match the label value model.aibrix.ai/name in the Deployment 
  namespace: default 
spec: 
  ports: 
    - name: serve 
      port: 6000 
      protocol: TCP 
      targetPort: 6000 
    - name: http 
      port: 8080 
      protocol: TCP 
      targetPort: 8080 
  selector: 
    model.aibrix.ai/name: sd-3 
  type: ClusterIP