apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: hunyuan-dit 
  labels: 
    model.aibrix.ai/name: hunyuan-dit 
    model.aibrix.ai/port: "6000" 
spec: 
  replicas: 1 
  strategy: 
    rollingUpdate: 
      maxSurge: 1 
      maxUnavailable: 1 
    type: RollingUpdate 
  selector: 
    matchLabels: 
      model.aibrix.ai/name: hunyuan-dit 
  template: 
    metadata: 
      labels: 
        model.aibrix.ai/name: hunyuan-dit 
    spec: 
      initContainers: 
        - command:             
            - aibrix_download 
            - --model-uri 
            - tos://aibrix-artifact-testing/models/HunyuanDiT-v1.2-Diffusers/
            - --local-dir 
            - /models/ 
          env: 
            - name: DOWNLOADER_NUM_THREADS 
              value: "16" 
            - name: TOS_ACCESS_KEY 
              valueFrom: 
                secretKeyRef: 
                  key: TOS_ACCESS_KEY 
                  name: tos-credential 
            - name: TOS_SECRET_KEY 
              valueFrom: 
                secretKeyRef: 
                  key: TOS_SECRET_KEY 
                  name: tos-credential 
            - name: TOS_ENDPOINT 
              value: https://tos-s3-cn-beijing.ivolces.com 
            - name: TOS_REGION 
              value: cn-beijing 
            - name: LOG_LEVEL
              value: DEBUG  
          image: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/runtime:v0.4.1-downloader-2
          name: init-model 
          volumeMounts: 
            - mountPath: /models 
              name: model-hostpath 
      containers: 
        - name: xdit-dev 
          image: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/xdit-dev:v0.20 #aibrix-cn-beijing.cr.volces.com/aibrix/vllm-openai:v0.8.5 
          imagePullPolicy: Always 
          command: ["sh", "-c"]
          args:
            - |
              python3 entrypoints/launch.py --model_path /models/HunyuanDiT-v1.2-Diffusers
          env: []
          volumeMounts: 
            - mountPath: /models 
              name: model-hostpath 
          resources: 
            limits: 
              nvidia.com/gpu: "1" 
              cpu: "10" # memory: "150G" 
            requests: 
              nvidia.com/gpu: "1" 
              cpu: "10" # memory: "150G" 
      volumes: 
        - name: model-hostpath 
          hostPath: 
            path: /root/models 
            type: DirectoryOrCreate 
        - name: model-mountpath
          hostPath: 
            path: /mnt/vdb/models
            type: DirectoryOrCreate   
                        
--- 


apiVersion: v1 
kind: Service 
metadata: 
  labels: 
    model.aibrix.ai/name: hunyuan-dit 
    prometheus-discovery: "true" 
  annotations: 
    prometheus.io/scrape: "true" 
    prometheus.io/port: "8080" 
  name: hunyuan-dit # Note: The Service name must match the label value model.aibrix.ai/name in the Deployment 
  namespace: default 
spec: 
  ports: 
    - name: serve 
      port: 8000 
      protocol: TCP 
      targetPort: 6000 
    - name: http 
      port: 8080 
      protocol: TCP 
      targetPort: 8080 
  selector: 
    model.aibrix.ai/name: hunyuan-dit 
  type: ClusterIP