apiVersion: apps/v1
kind: Deployment
metadata:
  name: hunyuan-dit
  labels:
    model.aibrix.ai/name: hunyuan-dit
    model.aibrix.ai/port: "6000"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      model.aibrix.ai/name: hunyuan-dit
  template:
    metadata:
      labels:
        model.aibrix.ai/name: hunyuan-dit
    spec:
      containers:
        - name: xdit-dev
          image: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/xdit-dev:v0.8 
          imagePullPolicy: Always
          command: ["sh", "-c"]
          args:
            - | 
              python3 entrypoints/launch.py --model_path /models/HunyuanDiT-v1.2-Diffusers
          env:
          volumeMounts:
            - name: model-vol
              mountPath: /models
              readOnly: true
            - mountPath: /dev/shm
              name: shared-mem
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "10"
              # memory: "150G"
            requests:
              nvidia.com/gpu: "1"
              cpu: "10"
              # memory: "150G"
      volumes: 
        - name: model-vol
          hostPath:
            path: /data01/models
            type: Directory
        - emptyDir:
            medium: Memory
          name: shared-mem
      nodeSelector:
        kubernetes.io/hostname: 192.168.0.6
---

apiVersion: v1
kind: Service
metadata:
  labels:
    model.aibrix.ai/name: hunyuan-dit
    prometheus-discovery: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
  name: hunyuan-dit # Note: The Service name must match the label value `model.aibrix.ai/name` in the Deployment
  namespace: default
spec:
  ports:
    - name: serve
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: http
      port: 6000
      protocol: TCP
      targetPort: 6000
  selector:
    model.aibrix.ai/name: hunyuan-dit
  type: ClusterIP
