apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-plugins
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: gateway-plugin
        env:
        - name: AIBRIX_ENABLE_VLLM_REMOTE_TOKENIZER
          value: "false"
        - name: AIBRIX_VLLM_TOKENIZER_ENDPOINT_TEMPLATE
          value: "http://%s:8000"
        - name: AIBRIX_TOKENIZER_HEALTH_CHECK_PERIOD
          value: "30s"
        - name: AIBRIX_TOKENIZER_TTL
          value: "5m"
        - name: AIBRIX_MAX_TOKENIZERS_PER_POOL
          value: "100"
        - name: AIBRIX_TOKENIZER_REQUEST_TIMEOUT
          value: "10s"