/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// CoschedulingSchedulingStrategySpecApplyConfiguration represents a declarative configuration of the CoschedulingSchedulingStrategySpec type for use
// with apply.
type CoschedulingSchedulingStrategySpecApplyConfiguration struct {
	MinMember              *int32           `json:"minMember,omitempty"`
	MinResources           *v1.ResourceList `json:"minResources,omitempty"`
	ScheduleTimeoutSeconds *int32           `json:"scheduleTimeoutSeconds,omitempty"`
}

// CoschedulingSchedulingStrategySpecApplyConfiguration constructs a declarative configuration of the CoschedulingSchedulingStrategySpec type for use with
// apply.
func CoschedulingSchedulingStrategySpec() *CoschedulingSchedulingStrategySpecApplyConfiguration {
	return &CoschedulingSchedulingStrategySpecApplyConfiguration{}
}

// WithMinMember sets the MinMember field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinMember field is set to the value of the last call.
func (b *CoschedulingSchedulingStrategySpecApplyConfiguration) WithMinMember(value int32) *CoschedulingSchedulingStrategySpecApplyConfiguration {
	b.MinMember = &value
	return b
}

// WithMinResources sets the MinResources field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinResources field is set to the value of the last call.
func (b *CoschedulingSchedulingStrategySpecApplyConfiguration) WithMinResources(value v1.ResourceList) *CoschedulingSchedulingStrategySpecApplyConfiguration {
	b.MinResources = &value
	return b
}

// WithScheduleTimeoutSeconds sets the ScheduleTimeoutSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ScheduleTimeoutSeconds field is set to the value of the last call.
func (b *CoschedulingSchedulingStrategySpecApplyConfiguration) WithScheduleTimeoutSeconds(value int32) *CoschedulingSchedulingStrategySpecApplyConfiguration {
	b.ScheduleTimeoutSeconds = &value
	return b
}
