/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vllm-project/aibrix/api/orchestration/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PauseConditionApplyConfiguration represents a declarative configuration of the PauseCondition type for use
// with apply.
type PauseConditionApplyConfiguration struct {
	Reason    *v1alpha1.PauseReason `json:"reason,omitempty"`
	StartTime *v1.Time              `json:"startTime,omitempty"`
}

// PauseConditionApplyConfiguration constructs a declarative configuration of the PauseCondition type for use with
// apply.
func PauseCondition() *PauseConditionApplyConfiguration {
	return &PauseConditionApplyConfiguration{}
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *PauseConditionApplyConfiguration) WithReason(value v1alpha1.PauseReason) *PauseConditionApplyConfiguration {
	b.Reason = &value
	return b
}

// WithStartTime sets the StartTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartTime field is set to the value of the last call.
func (b *PauseConditionApplyConfiguration) WithStartTime(value v1.Time) *PauseConditionApplyConfiguration {
	b.StartTime = &value
	return b
}
