/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RoleStatusApplyConfiguration represents a declarative configuration of the RoleStatus type for use
// with apply.
type RoleStatusApplyConfiguration struct {
	Name                 *string `json:"name,omitempty"`
	Replicas             *int32  `json:"replicas,omitempty"`
	ReadyReplicas        *int32  `json:"readyReplicas,omitempty"`
	NotReadyReplicas     *int32  `json:"notReadyReplicas,omitempty"`
	UpdatedReplicas      *int32  `json:"updatedReplicas,omitempty"`
	UpdatedReadyReplicas *int32  `json:"updatedReadyReplicas,omitempty"`
}

// RoleStatusApplyConfiguration constructs a declarative configuration of the RoleStatus type for use with
// apply.
func RoleStatus() *RoleStatusApplyConfiguration {
	return &RoleStatusApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *RoleStatusApplyConfiguration) WithName(value string) *RoleStatusApplyConfiguration {
	b.Name = &value
	return b
}

// WithReplicas sets the Replicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Replicas field is set to the value of the last call.
func (b *RoleStatusApplyConfiguration) WithReplicas(value int32) *RoleStatusApplyConfiguration {
	b.Replicas = &value
	return b
}

// WithReadyReplicas sets the ReadyReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReadyReplicas field is set to the value of the last call.
func (b *RoleStatusApplyConfiguration) WithReadyReplicas(value int32) *RoleStatusApplyConfiguration {
	b.ReadyReplicas = &value
	return b
}

// WithNotReadyReplicas sets the NotReadyReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NotReadyReplicas field is set to the value of the last call.
func (b *RoleStatusApplyConfiguration) WithNotReadyReplicas(value int32) *RoleStatusApplyConfiguration {
	b.NotReadyReplicas = &value
	return b
}

// WithUpdatedReplicas sets the UpdatedReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdatedReplicas field is set to the value of the last call.
func (b *RoleStatusApplyConfiguration) WithUpdatedReplicas(value int32) *RoleStatusApplyConfiguration {
	b.UpdatedReplicas = &value
	return b
}

// WithUpdatedReadyReplicas sets the UpdatedReadyReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UpdatedReadyReplicas field is set to the value of the last call.
func (b *RoleStatusApplyConfiguration) WithUpdatedReadyReplicas(value int32) *RoleStatusApplyConfiguration {
	b.UpdatedReadyReplicas = &value
	return b
}
