apiVersion: orchestration.aibrix.ai/v1alpha1
kind: RoleSet
metadata:
  labels:
    app.kubernetes.io/name: aibrix
    app.kubernetes.io/managed-by: kustomize
  name: roleset-sample
spec:
  # TODO(user): Add fields here
