apiVersion: orchestration.aibrix.ai/v1alpha1
kind: KVCache
metadata:
  name: aibrix-deepseek-coder-33b-kvcache
  namespace: aibrix-system
spec:
  replicas: 1
  service:
    type: ClusterIP
    port: 9600
  cacheSpec:
    image: aibrix/kvcache:20241120
    imagePullPolicy: IfNotPresent
