apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aibrix-system

namePrefix: aibrix-

resources:
- ../../../gateway/gateway-plugin

images:
- name: busybox
  newName: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/busybox
  newTag: stable
- name: gateway-plugins
  newName: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/gateway-plugins
  newTag: nightly