apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: metric-exporter-testing
  namespace: default
spec:
  endpoints:
    - interval: 15s
      path: /metrics
      port: metrics
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      prometheus-discovery: "true"

