/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vllm-project/aibrix/api/autoscaling/v1alpha1"
)

// CircuitBreakerConfigApplyConfiguration represents a declarative configuration of the CircuitBreakerConfig type for use
// with apply.
type CircuitBreakerConfigApplyConfiguration struct {
	Enabled           *bool                          `json:"enabled,omitempty"`
	Action            *v1alpha1.CircuitBreakerAction `json:"action,omitempty"`
	FailureThreshold  *int32                         `json:"failureThreshold,omitempty"`
	RecoveryThreshold *int32                         `json:"recoveryThreshold,omitempty"`
}

// CircuitBreakerConfigApplyConfiguration constructs a declarative configuration of the CircuitBreakerConfig type for use with
// apply.
func CircuitBreakerConfig() *CircuitBreakerConfigApplyConfiguration {
	return &CircuitBreakerConfigApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *CircuitBreakerConfigApplyConfiguration) WithEnabled(value bool) *CircuitBreakerConfigApplyConfiguration {
	b.Enabled = &value
	return b
}

// WithAction sets the Action field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Action field is set to the value of the last call.
func (b *CircuitBreakerConfigApplyConfiguration) WithAction(value v1alpha1.CircuitBreakerAction) *CircuitBreakerConfigApplyConfiguration {
	b.Action = &value
	return b
}

// WithFailureThreshold sets the FailureThreshold field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailureThreshold field is set to the value of the last call.
func (b *CircuitBreakerConfigApplyConfiguration) WithFailureThreshold(value int32) *CircuitBreakerConfigApplyConfiguration {
	b.FailureThreshold = &value
	return b
}

// WithRecoveryThreshold sets the RecoveryThreshold field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RecoveryThreshold field is set to the value of the last call.
func (b *CircuitBreakerConfigApplyConfiguration) WithRecoveryThreshold(value int32) *CircuitBreakerConfigApplyConfiguration {
	b.RecoveryThreshold = &value
	return b
}
