/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vllm-project/aibrix/api/autoscaling/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// CircuitBreakerStatusApplyConfiguration represents a declarative configuration of the CircuitBreakerStatus type for use
// with apply.
type CircuitBreakerStatusApplyConfiguration struct {
	State              *v1alpha1.CircuitBreakerState  `json:"state,omitempty"`
	Action             *v1alpha1.CircuitBreakerAction `json:"action,omitempty"`
	FailureCount       *int32                         `json:"failureCount,omitempty"`
	RecoveryCount      *int32                         `json:"recoveryCount,omitempty"`
	ProtectedReplicas  *int32                         `json:"protectedReplicas,omitempty"`
	Reason             *string                        `json:"reason,omitempty"`
	LastTransitionTime *v1.Time                       `json:"lastTransitionTime,omitempty"`
}

// CircuitBreakerStatusApplyConfiguration constructs a declarative configuration of the CircuitBreakerStatus type for use with
// apply.
func CircuitBreakerStatus() *CircuitBreakerStatusApplyConfiguration {
	return &CircuitBreakerStatusApplyConfiguration{}
}

// WithState sets the State field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the State field is set to the value of the last call.
func (b *CircuitBreakerStatusApplyConfiguration) WithState(value v1alpha1.CircuitBreakerState) *CircuitBreakerStatusApplyConfiguration {
	b.State = &value
	return b
}

// WithAction sets the Action field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Action field is set to the value of the last call.
func (b *CircuitBreakerStatusApplyConfiguration) WithAction(value v1alpha1.CircuitBreakerAction) *CircuitBreakerStatusApplyConfiguration {
	b.Action = &value
	return b
}

// WithFailureCount sets the FailureCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the FailureCount field is set to the value of the last call.
func (b *CircuitBreakerStatusApplyConfiguration) WithFailureCount(value int32) *CircuitBreakerStatusApplyConfiguration {
	b.FailureCount = &value
	return b
}

// WithRecoveryCount sets the RecoveryCount field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RecoveryCount field is set to the value of the last call.
func (b *CircuitBreakerStatusApplyConfiguration) WithRecoveryCount(value int32) *CircuitBreakerStatusApplyConfiguration {
	b.RecoveryCount = &value
	return b
}

// WithProtectedReplicas sets the ProtectedReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ProtectedReplicas field is set to the value of the last call.
func (b *CircuitBreakerStatusApplyConfiguration) WithProtectedReplicas(value int32) *CircuitBreakerStatusApplyConfiguration {
	b.ProtectedReplicas = &value
	return b
}

// WithReason sets the Reason field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Reason field is set to the value of the last call.
func (b *CircuitBreakerStatusApplyConfiguration) WithReason(value string) *CircuitBreakerStatusApplyConfiguration {
	b.Reason = &value
	return b
}

// WithLastTransitionTime sets the LastTransitionTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastTransitionTime field is set to the value of the last call.
func (b *CircuitBreakerStatusApplyConfiguration) WithLastTransitionTime(value v1.Time) *CircuitBreakerStatusApplyConfiguration {
	b.LastTransitionTime = &value
	return b
}
