/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ElasticEPScalingStatusApplyConfiguration represents a declarative configuration of the ElasticEPScalingStatus type for use
// with apply.
type ElasticEPScalingStatusApplyConfiguration struct {
	InProgress         *bool    `json:"inProgress,omitempty"`
	ObservedEngines    *int32   `json:"observedEngines,omitempty"`
	ScalingEngines     *int32   `json:"scalingEngines,omitempty"`
	LastTransitionTime *v1.Time `json:"lastTransitionTime,omitempty"`
}

// ElasticEPScalingStatusApplyConfiguration constructs a declarative configuration of the ElasticEPScalingStatus type for use with
// apply.
func ElasticEPScalingStatus() *ElasticEPScalingStatusApplyConfiguration {
	return &ElasticEPScalingStatusApplyConfiguration{}
}

// WithInProgress sets the InProgress field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InProgress field is set to the value of the last call.
func (b *ElasticEPScalingStatusApplyConfiguration) WithInProgress(value bool) *ElasticEPScalingStatusApplyConfiguration {
	b.InProgress = &value
	return b
}

// WithObservedEngines sets the ObservedEngines field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedEngines field is set to the value of the last call.
func (b *ElasticEPScalingStatusApplyConfiguration) WithObservedEngines(value int32) *ElasticEPScalingStatusApplyConfiguration {
	b.ObservedEngines = &value
	return b
}

// WithScalingEngines sets the ScalingEngines field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ScalingEngines field is set to the value of the last call.
func (b *ElasticEPScalingStatusApplyConfiguration) WithScalingEngines(value int32) *ElasticEPScalingStatusApplyConfiguration {
	b.ScalingEngines = &value
	return b
}

// WithLastTransitionTime sets the LastTransitionTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastTransitionTime field is set to the value of the last call.
func (b *ElasticEPScalingStatusApplyConfiguration) WithLastTransitionTime(value v1.Time) *ElasticEPScalingStatusApplyConfiguration {
	b.LastTransitionTime = &value
	return b
}
