/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vllm-project/aibrix/api/autoscaling/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// PredictiveStatusApplyConfiguration represents a declarative configuration of the PredictiveStatus type for use
// with apply.
type PredictiveStatusApplyConfiguration struct {
	Mode              *v1alpha1.PredictiveMode `json:"mode,omitempty"`
	Metric            *string                  `json:"metric,omitempty"`
	ObservedValue     *string                  `json:"observedValue,omitempty"`
	PredictedValue    *string                  `json:"predictedValue,omitempty"`
	PredictedReplicas *int32                   `json:"predictedReplicas,omitempty"`
	ReactiveReplicas  *int32                   `json:"reactiveReplicas,omitempty"`
	WouldBeReplicas   *int32                   `json:"wouldBeReplicas,omitempty"`
	LastUpdated       *v1.Time                 `json:"lastUpdated,omitempty"`
}

// PredictiveStatusApplyConfiguration constructs a declarative configuration of the PredictiveStatus type for use with
// apply.
func PredictiveStatus() *PredictiveStatusApplyConfiguration {
	return &PredictiveStatusApplyConfiguration{}
}

// WithMode sets the Mode field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Mode field is set to the value of the last call.
func (b *PredictiveStatusApplyConfiguration) WithMode(value v1alpha1.PredictiveMode) *PredictiveStatusApplyConfiguration {
	b.Mode = &value
	return b
}

// WithMetric sets the Metric field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Metric field is set to the value of the last call.
func (b *PredictiveStatusApplyConfiguration) WithMetric(value string) *PredictiveStatusApplyConfiguration {
	b.Metric = &value
	return b
}

// WithObservedValue sets the ObservedValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ObservedValue field is set to the value of the last call.
func (b *PredictiveStatusApplyConfiguration) WithObservedValue(value string) *PredictiveStatusApplyConfiguration {
	b.ObservedValue = &value
	return b
}

// WithPredictedValue sets the PredictedValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PredictedValue field is set to the value of the last call.
func (b *PredictiveStatusApplyConfiguration) WithPredictedValue(value string) *PredictiveStatusApplyConfiguration {
	b.PredictedValue = &value
	return b
}

// WithPredictedReplicas sets the PredictedReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PredictedReplicas field is set to the value of the last call.
func (b *PredictiveStatusApplyConfiguration) WithPredictedReplicas(value int32) *PredictiveStatusApplyConfiguration {
	b.PredictedReplicas = &value
	return b
}

// WithReactiveReplicas sets the ReactiveReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ReactiveReplicas field is set to the value of the last call.
func (b *PredictiveStatusApplyConfiguration) WithReactiveReplicas(value int32) *PredictiveStatusApplyConfiguration {
	b.ReactiveReplicas = &value
	return b
}

// WithWouldBeReplicas sets the WouldBeReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the WouldBeReplicas field is set to the value of the last call.
func (b *PredictiveStatusApplyConfiguration) WithWouldBeReplicas(value int32) *PredictiveStatusApplyConfiguration {
	b.WouldBeReplicas = &value
	return b
}

// WithLastUpdated sets the LastUpdated field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LastUpdated field is set to the value of the last call.
func (b *PredictiveStatusApplyConfiguration) WithLastUpdated(value v1.Time) *PredictiveStatusApplyConfiguration {
	b.LastUpdated = &value
	return b
}
