/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// ScheduledReplicaBoundsApplyConfiguration represents a declarative configuration of the ScheduledReplicaBounds type for use
// with apply.
type ScheduledReplicaBoundsApplyConfiguration struct {
	Name        *string      `json:"name,omitempty"`
	Timezone    *string      `json:"timezone,omitempty"`
	StartTime   *v1.Time     `json:"startTime,omitempty"`
	EndTime     *v1.Time     `json:"endTime,omitempty"`
	Cron        *string      `json:"cron,omitempty"`
	Duration    *v1.Duration `json:"duration,omitempty"`
	MinReplicas *int32       `json:"minReplicas,omitempty"`
	MaxReplicas *int32       `json:"maxReplicas,omitempty"`
}

// ScheduledReplicaBoundsApplyConfiguration constructs a declarative configuration of the ScheduledReplicaBounds type for use with
// apply.
func ScheduledReplicaBounds() *ScheduledReplicaBoundsApplyConfiguration {
	return &ScheduledReplicaBoundsApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ScheduledReplicaBoundsApplyConfiguration) WithName(value string) *ScheduledReplicaBoundsApplyConfiguration {
	b.Name = &value
	return b
}

// WithTimezone sets the Timezone field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timezone field is set to the value of the last call.
func (b *ScheduledReplicaBoundsApplyConfiguration) WithTimezone(value string) *ScheduledReplicaBoundsApplyConfiguration {
	b.Timezone = &value
	return b
}

// WithStartTime sets the StartTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartTime field is set to the value of the last call.
func (b *ScheduledReplicaBoundsApplyConfiguration) WithStartTime(value v1.Time) *ScheduledReplicaBoundsApplyConfiguration {
	b.StartTime = &value
	return b
}

// WithEndTime sets the EndTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndTime field is set to the value of the last call.
func (b *ScheduledReplicaBoundsApplyConfiguration) WithEndTime(value v1.Time) *ScheduledReplicaBoundsApplyConfiguration {
	b.EndTime = &value
	return b
}

// WithCron sets the Cron field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Cron field is set to the value of the last call.
func (b *ScheduledReplicaBoundsApplyConfiguration) WithCron(value string) *ScheduledReplicaBoundsApplyConfiguration {
	b.Cron = &value
	return b
}

// WithDuration sets the Duration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Duration field is set to the value of the last call.
func (b *ScheduledReplicaBoundsApplyConfiguration) WithDuration(value v1.Duration) *ScheduledReplicaBoundsApplyConfiguration {
	b.Duration = &value
	return b
}

// WithMinReplicas sets the MinReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinReplicas field is set to the value of the last call.
func (b *ScheduledReplicaBoundsApplyConfiguration) WithMinReplicas(value int32) *ScheduledReplicaBoundsApplyConfiguration {
	b.MinReplicas = &value
	return b
}

// WithMaxReplicas sets the MaxReplicas field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxReplicas field is set to the value of the last call.
func (b *ScheduledReplicaBoundsApplyConfiguration) WithMaxReplicas(value int32) *ScheduledReplicaBoundsApplyConfiguration {
	b.MaxReplicas = &value
	return b
}
