---
# ServiceAccount for EPP
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qwen2-7b-epp
  namespace: default

---
# EPP Service
apiVersion: v1
kind: Service
metadata:
  name: qwen2-7b-epp
  namespace: default
spec:
  selector:
    app: qwen2-7b-epp
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
      appProtocol: http2
  type: ClusterIP

---
# EPP Deployment (using your custom image & config)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen2-7b-epp
  namespace: default
  labels:
    app: qwen2-7b-epp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen2-7b-epp
  template:
    metadata:
      labels:
        app: qwen2-7b-epp
    spec:
      serviceAccountName: qwen2-7b-epp
      terminationGracePeriodSeconds: 130
      containers:
        - name: epp
          image: ghcr.io/llm-d/llm-d-inference-scheduler:latest
          imagePullPolicy: IfNotPresent
          args:
            - --pool-name
            - "qwen2-7b"
            - --pool-namespace
            - "default"
            - --v
            - "4"
            - --zap-encoder
            - "json"
            - --grpc-port
            - "9002"
            - --grpc-health-port
            - "9003"
            - --config-file
            - "/etc/epp/epp-config.yaml"
          env:
            - name: PYTHONHASHSEED
              value: "42"
          ports:
            - containerPort: 5557   # optional, if used
            - containerPort: 9002   # gRPC serving
            - containerPort: 9003   # health check
            - name: metrics
              containerPort: 9090
          livenessProbe:
            grpc:
              port: 9003
              service: envoy.service.ext_proc.v3.ExternalProcessor
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            grpc:
              port: 9003
              service: envoy.service.ext_proc.v3.ExternalProcessor
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: epp-config
              mountPath: /etc/epp
            - name: cache
              mountPath: /cache
      volumes:
        - name: epp-config
          configMap:
            name: qwen2-7b-epp-config
        - name: cache
          emptyDir: {}

---
# RBAC: Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qwen2-7b-epp-pod-read
  namespace: default
rules:
  - apiGroups: ["inference.networking.x-k8s.io"]
    resources: ["inferenceobjectives", "inferencepools"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["inference.networking.k8s.io"]
    resources: ["inferencepools"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]

---
# RBAC: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qwen2-7b-epp-pod-read-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: qwen2-7b-epp
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: qwen2-7b-epp-pod-read

---
# ConfigMap for EPP plugins
apiVersion: v1
kind: ConfigMap
metadata:
  name: qwen2-7b-epp-config
  namespace: default
data:
  epp-config.yaml: |
    apiVersion: inference.networking.x-k8s.io/v1alpha1
    kind: EndpointPickerConfig
    plugins:
      - type: by-label
        name: "prefill"
        parameters:
          label: "role"
          validValues: ["prefill"]
      - type: by-label
        name: "decode"
        parameters:
          label: "role"
          validValues: ["decode", "both"]
      - type: prefix-cache-scorer
        parameters:
          hashBlockSize: 5
          maxPrefixBlocksToMatch: 256
          lruCapacityPerServer: 31250
      - type: max-score-picker
      - type: prefill-header-handler
      - type: pd-profile-handler
        parameters:
          threshold: 0
          hashBlockSize: 5
          primaryPort: 8000
    schedulingProfiles:
      - name: prefill
        plugins:
          - pluginRef: prefill
          - pluginRef: max-score-picker
          - pluginRef: prefix-cache-scorer
            weight: 2
      - name: decode
        plugins:
          - pluginRef: decode
          - pluginRef: max-score-picker
          - pluginRef: prefix-cache-scorer
            weight: 2
