apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: cogvideox-2b 
  labels: 
    model.aibrix.ai/name: cogvideox-2b 
    model.aibrix.ai/port: "6000" 
spec: 
  replicas: 1 
  strategy: 
    rollingUpdate: 
      maxSurge: 1 
      maxUnavailable: 1 
    type: RollingUpdate 
  selector: 
    matchLabels: 
      model.aibrix.ai/name: cogvideox-2b 
  template: 
    metadata: 
      labels: 
        model.aibrix.ai/name: cogvideox-2b 
        model.aibrix.ai/port: "6000" 
    spec: 
      initContainers: 
        - command:             
            - aibrix_download 
            - --model-uri 
            - tos://aibrix-artifact-testing/models/CogVideoX-2b/
            - --local-dir 
            - /models/ 
          env: 
            - name: DOWNLOADER_NUM_THREADS 
              value: "16" 
            - name: TOS_ACCESS_KEY 
              valueFrom: 
                secretKeyRef: 
                  key: TOS_ACCESS_KEY 
                  name: tos-credential 
            - name: TOS_SECRET_KEY 
              valueFrom: 
                secretKeyRef: 
                  key: TOS_SECRET_KEY 
                  name: tos-credential 
            - name: TOS_ENDPOINT 
              value: https://tos-s3-cn-beijing.ivolces.com 
            - name: TOS_REGION 
              value: cn-beijing 
            - name: LOG_LEVEL
              value: DEBUG  
          image: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/runtime:v0.4.1-mm1
          name: init-model 
          volumeMounts: 
            - mountPath: /models 
              name: model-hostpath 
      containers: 
        - name: xdit-dev 
          image: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/xdit-dev:customized-v1  
          imagePullPolicy: Always 
          command: ["sh", "-c"]
          args:
            - |
              python3 entrypoints/launch_video.py --model_path /models/CogVideoX-2b --ulysses_parallel_degree 2 --ring_degree 2 --world_size 4 --host 0.0.0.0 --port 6000
          env: [] 
          volumeMounts: 
            - mountPath: /models 
              name: model-hostpath 
            - mountPath: /dev/shm
              name: dshm
            - name: shared-data
              mountPath: /shared
          resources: 
            limits: 
              nvidia.com/gpu: "4" 
              cpu: "10" 
            requests: 
              nvidia.com/gpu: "4" 
              cpu: "10" 
        - name: aibrix-runtime
          image: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/runtime:v0.4.1-mm1
          command:
            - aibrix_runtime
            - --port
            - "8080"
          env:
            - name: INFERENCE_ENGINE
              value: vllm
            - name: INFERENCE_ENGINE_ENDPOINT
              value: http://localhost:8000
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: shared-data
              mountPath: /shared
      nodeSelector:
        kubernetes.io/hostname: 192.168.0.6
      volumes: 
        - name: model-hostpath 
          hostPath: 
            path: /data01/models
            type: DirectoryOrCreate 
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 16Gi   
        - name: shared-data
          emptyDir: {}              
--- 


apiVersion: v1 
kind: Service 
metadata: 
  labels: 
    model.aibrix.ai/name: cogvideox-2b 
    prometheus-discovery: "true" 
  annotations: 
    prometheus.io/scrape: "true" 
    prometheus.io/port: "8080" 
  name: cogvideox-2b 
  namespace: default 
spec: 
  ports: 
    - name: serve 
      port: 6000 
      protocol: TCP 
      targetPort: 6000 
    - name: http 
      port: 8080 
      protocol: TCP 
      targetPort: 8080 
  selector: 
    model.aibrix.ai/name: cogvideox-2b 
  type: ClusterIP