/*
Copyright 2026 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package transfer

import (
	"fmt"
	"io"
	"net/http"
	"sync"
	"time"

	"github.com/bytedance/sonic"
	"github.com/vllm-project/aibrix/pkg/types"
	"github.com/vllm-project/aibrix/pkg/utils"
	v1 "k8s.io/api/core/v1"
	"k8s.io/klog/v2"
)

// mooncakeBootstrapPort is the HTTP port of the MooncakeBootstrapServer running
// on each prefill pod's global-rank-0 worker. It must match vLLM's
// VLLM_MOONCAKE_BOOTSTRAP_PORT (default 8998). AIBrix exposes its own env var
// so operators can align both sides from a single place.
var mooncakeBootstrapPort = utils.LoadEnvInt("AIBRIX_MOONCAKE_BOOTSTRAP_PORT", 8998)

// mooncakeBootstrapQueryTimeout bounds a single GET /query to the bootstrap server.
const mooncakeBootstrapQueryTimeout = 5 * time.Second

// mooncakeBootstrapCacheTTL is how long a cached bootstrap entry is considered
// fresh. Mooncake engine_id is stable for the lifetime of a prefill pod, but we
// re-query periodically so that a recreated pod (new engine_id) is picked up.
const mooncakeBootstrapCacheTTL = 5 * time.Minute

// bootstrapHTTPClient is shared across requests so TCP connections to the
// bootstrap server are pooled. It is safe for concurrent use.
var bootstrapHTTPClient = &http.Client{Timeout: mooncakeBootstrapQueryTimeout}

// mooncakeBootstrapInfo is the cached result of querying a prefill pod's
// MooncakeBootstrapServer GET /query endpoint. Only the fields needed to
// construct the decode-side kv_transfer_params are kept.
type mooncakeBootstrapInfo struct {
	engineID      string // remote_engine_id for the decode pod
	bootstrapAddr string // http://{prefillPodIP}:{port}, decode appends /query
	fetchedAt     time.Time
}

// bootstrapCache is a process-wide cache keyed by prefill pod IP. The
// MooncakeAgent is stateless (a new instance is created per request via the
// factory), so the cache must live at package scope to be effective across
// requests. Concurrent gateway goroutines share it, hence the RWMutex.
var bootstrapCache = struct {
	sync.RWMutex
	m map[string]*mooncakeBootstrapInfo
}{
	m: make(map[string]*mooncakeBootstrapInfo),
}

func init() {
	Register(ConnectorTypeMooncake, func() KVTransferAgent { return &MooncakeAgent{} })
}

// MooncakeAgent implements KVTransferAgent for the Mooncake KV transfer backend.
//
// Mooncake differs from SHFS/NIXL in a critical way: the vLLM
// MooncakeConnector.request_finished() returns None for kv_transfer_params
// (P<->D KV transfer happens over a direct ZMQ+RDMA channel, not via the API
// response). Therefore the SHFS flow of "extract kv_transfer_params from the
// prefill response and forward to decode" does not work. Instead:
//
//   - AugmentPrefillRequest injects a router-generated transfer_id so the
//     prefill-side connector can correlate the send.
//   - MergePrefillResponse queries the prefill pod's MooncakeBootstrapServer
//     to obtain the engine_id, then constructs the decode-side kv_transfer_params
//     (do_remote_prefill=true + remote_bootstrap_addr) so the decode-side
//     connector can locate the prefill workers and pull KV via ZMQ.
type MooncakeAgent struct{}

func (a *MooncakeAgent) Type() string { return ConnectorTypeMooncake }

// AugmentPrefillRequest injects kv_transfer_params into the prefill request so
// the P-side MooncakeConnector knows to send KV to the decode pod after prefill
// completes (do_remote_decode=true). transfer_id is generated by the router
// because Mooncake's request_finished does not return one (unlike NIXL).
//
// The same transfer_id is reused in MergePrefillResponse for the decode side,
// so P and D can correlate the transfer.
func (a *MooncakeAgent) AugmentPrefillRequest(
	routingCtx *types.RoutingContext,
	_ *v1.Pod,
	completionRequest map[string]any,
) error {
	if routingCtx == nil {
		return fmt.Errorf("routing context is nil")
	}
	if completionRequest == nil {
		return fmt.Errorf("completion request map is nil")
	}
	completionRequest["kv_transfer_params"] = map[string]any{
		"do_remote_decode":  true,
		"do_remote_prefill": false,
		"transfer_id":       fmt.Sprintf("xfer-%s", routingCtx.RequestID),
	}
	return nil
}

// MergePrefillResponse constructs the decode-side kv_transfer_params.
//
// The prefill response itself carries no kv_transfer_params for Mooncake (the
// argument is intentionally ignored), so we resolve the prefill pod's
// MooncakeBootstrapServer instead: GET http://{prefillPodIP}:{port}/query
// returns {dp_rank: {engine_id, worker_addr}}; we take dp_rank 0's engine_id.
// The decode-side connector then queries the same bootstrap_addr to discover
// the prefill workers' ZMQ addresses and pulls KV via RDMA.
func (a *MooncakeAgent) MergePrefillResponse(
	routingCtx *types.RoutingContext,
	_ map[string]any, // prefillResponse is unused: Mooncake returns no kv_transfer_params
	prefillPod *v1.Pod,
) error {
	if routingCtx == nil {
		return fmt.Errorf("routing context is nil")
	}
	if prefillPod == nil {
		return fmt.Errorf("prefill pod is nil")
	}

	var originalRequest map[string]any
	if err := sonic.Unmarshal(routingCtx.ReqBody, &originalRequest); err != nil {
		return fmt.Errorf("failed to unmarshal original request body: %w", err)
	}
	if originalRequest == nil {
		return fmt.Errorf("original request body is empty or null")
	}

	info, err := getMooncakeBootstrapInfo(routingCtx, prefillPod)
	if err != nil {
		return fmt.Errorf("failed to resolve mooncake bootstrap info for prefill pod %s: %w",
			prefillPod.Name, err)
	}

	originalRequest["kv_transfer_params"] = map[string]any{
		"do_remote_decode":      false,
		"do_remote_prefill":     true,
		"remote_engine_id":      info.engineID,
		"remote_bootstrap_addr": info.bootstrapAddr,
		"transfer_id":           fmt.Sprintf("xfer-%s", routingCtx.RequestID),
	}

	updatedReqBody, err := sonic.Marshal(originalRequest)
	if err != nil {
		return fmt.Errorf("failed to marshal updated request body: %w", err)
	}
	routingCtx.ReqBody = updatedReqBody

	klog.InfoS("updated routing context with kv_transfer_params (Mooncake)",
		"request_id", routingCtx.RequestID,
		"prefill_pod", prefillPod.Name,
		"prefill_host", prefillPod.Status.PodIP,
		"remote_engine_id", info.engineID,
		"remote_bootstrap_addr", info.bootstrapAddr,
		"kv_connector_type", ConnectorTypeMooncake)
	return nil
}

// getMooncakeBootstrapInfo returns the (cached) engine_id and bootstrap address
// for a prefill pod. On cache miss or TTL expiry it queries the pod's
// MooncakeBootstrapServer GET /query. The result is cached per pod IP so we do
// not add a per-request HTTP round-trip in the hot path.
func getMooncakeBootstrapInfo(routingCtx *types.RoutingContext, prefillPod *v1.Pod) (*mooncakeBootstrapInfo, error) {
	if prefillPod == nil {
		return nil, fmt.Errorf("prefill pod is nil")
	}
	podIP := prefillPod.Status.PodIP
	if podIP == "" {
		return nil, fmt.Errorf("prefill pod %s has no PodIP yet", prefillPod.Name)
	}

	// Fast path: serve from cache if fresh.
	bootstrapCache.RLock()
	info, ok := bootstrapCache.m[podIP]
	bootstrapCache.RUnlock()
	if ok && time.Since(info.fetchedAt) < mooncakeBootstrapCacheTTL {
		return info, nil
	}

	// Slow path: query the bootstrap server.
	bootstrapAddr := fmt.Sprintf("http://%s:%d", podIP, mooncakeBootstrapPort)
	queryURL := bootstrapAddr + "/query"

	req, err := http.NewRequestWithContext(routingCtx, http.MethodGet, queryURL, nil)
	if err != nil {
		return nil, fmt.Errorf("create request for mooncake bootstrap %s: %w", queryURL, err)
	}
	resp, err := bootstrapHTTPClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("query mooncake bootstrap %s: %w", queryURL, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("mooncake bootstrap %s returned status %d",
			queryURL, resp.StatusCode)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("read mooncake bootstrap /query body: %w", err)
	}

	// /query returns dict[dp_rank, EngineEntry]; JSON object keys are strings.
	// EngineEntry = {engine_id: str, worker_addr: {tp_rank: {pp_rank: addr}}}.
	// We only need engine_id (from dp_rank 0, or the first available).
	var workers map[string]struct {
		EngineID   string                       `json:"engine_id"`
		WorkerAddr map[string]map[string]string `json:"worker_addr"`
	}
	if err := sonic.Unmarshal(body, &workers); err != nil {
		return nil, fmt.Errorf("decode mooncake bootstrap /query response: %w", err)
	}

	entry, ok := workers["0"]
	if !ok {
		// Fall back to the first dp_rank if "0" is absent.
		for _, e := range workers {
			entry = e
			ok = true
			break
		}
	}
	if !ok || entry.EngineID == "" {
		return nil, fmt.Errorf("mooncake bootstrap %s returned no engine_id", queryURL)
	}

	info = &mooncakeBootstrapInfo{
		engineID:      entry.EngineID,
		bootstrapAddr: bootstrapAddr,
		fetchedAt:     time.Now(),
	}

	// Prune stale cache entries while holding the write lock to prevent
	// unbounded growth as pods are created and destroyed.
	bootstrapCache.Lock()
	for ip, cached := range bootstrapCache.m {
		if time.Since(cached.fetchedAt) > mooncakeBootstrapCacheTTL {
			delete(bootstrapCache.m, ip)
		}
	}
	bootstrapCache.m[podIP] = info
	bootstrapCache.Unlock()

	klog.V(4).InfoS("fetched mooncake bootstrap info",
		"prefill_pod", prefillPod.Name, "pod_ip", podIP,
		"engine_id", info.engineID, "bootstrap_addr", bootstrapAddr)
	return info, nil
}
