/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "github.com/vllm-project/aibrix/api/model/v1alpha1"
	modelv1alpha1 "github.com/vllm-project/aibrix/pkg/client/applyconfiguration/model/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeModelWarmups implements ModelWarmupInterface
type FakeModelWarmups struct {
	Fake *FakeModelV1alpha1
	ns   string
}

var modelwarmupsResource = v1alpha1.SchemeGroupVersion.WithResource("modelwarmups")

var modelwarmupsKind = v1alpha1.SchemeGroupVersion.WithKind("ModelWarmup")

// Get takes name of the modelWarmup, and returns the corresponding modelWarmup object, and an error if there is any.
func (c *FakeModelWarmups) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ModelWarmup, err error) {
	emptyResult := &v1alpha1.ModelWarmup{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(modelwarmupsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.ModelWarmup), err
}

// List takes label and field selectors, and returns the list of ModelWarmups that match those selectors.
func (c *FakeModelWarmups) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ModelWarmupList, err error) {
	emptyResult := &v1alpha1.ModelWarmupList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(modelwarmupsResource, modelwarmupsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ModelWarmupList{ListMeta: obj.(*v1alpha1.ModelWarmupList).ListMeta}
	for _, item := range obj.(*v1alpha1.ModelWarmupList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested modelWarmups.
func (c *FakeModelWarmups) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(modelwarmupsResource, c.ns, opts))

}

// Create takes the representation of a modelWarmup and creates it.  Returns the server's representation of the modelWarmup, and an error, if there is any.
func (c *FakeModelWarmups) Create(ctx context.Context, modelWarmup *v1alpha1.ModelWarmup, opts v1.CreateOptions) (result *v1alpha1.ModelWarmup, err error) {
	emptyResult := &v1alpha1.ModelWarmup{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(modelwarmupsResource, c.ns, modelWarmup, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.ModelWarmup), err
}

// Update takes the representation of a modelWarmup and updates it. Returns the server's representation of the modelWarmup, and an error, if there is any.
func (c *FakeModelWarmups) Update(ctx context.Context, modelWarmup *v1alpha1.ModelWarmup, opts v1.UpdateOptions) (result *v1alpha1.ModelWarmup, err error) {
	emptyResult := &v1alpha1.ModelWarmup{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(modelwarmupsResource, c.ns, modelWarmup, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.ModelWarmup), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeModelWarmups) UpdateStatus(ctx context.Context, modelWarmup *v1alpha1.ModelWarmup, opts v1.UpdateOptions) (result *v1alpha1.ModelWarmup, err error) {
	emptyResult := &v1alpha1.ModelWarmup{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(modelwarmupsResource, "status", c.ns, modelWarmup, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.ModelWarmup), err
}

// Delete takes name of the modelWarmup and deletes it. Returns an error if one occurs.
func (c *FakeModelWarmups) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(modelwarmupsResource, c.ns, name, opts), &v1alpha1.ModelWarmup{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeModelWarmups) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(modelwarmupsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ModelWarmupList{})
	return err
}

// Patch applies the patch and returns the patched modelWarmup.
func (c *FakeModelWarmups) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ModelWarmup, err error) {
	emptyResult := &v1alpha1.ModelWarmup{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(modelwarmupsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.ModelWarmup), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied modelWarmup.
func (c *FakeModelWarmups) Apply(ctx context.Context, modelWarmup *modelv1alpha1.ModelWarmupApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.ModelWarmup, err error) {
	if modelWarmup == nil {
		return nil, fmt.Errorf("modelWarmup provided to Apply must not be nil")
	}
	data, err := json.Marshal(modelWarmup)
	if err != nil {
		return nil, err
	}
	name := modelWarmup.Name
	if name == nil {
		return nil, fmt.Errorf("modelWarmup.Name must be provided to Apply")
	}
	emptyResult := &v1alpha1.ModelWarmup{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(modelwarmupsResource, c.ns, *name, types.ApplyPatchType, data, opts.ToPatchOptions()), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.ModelWarmup), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeModelWarmups) ApplyStatus(ctx context.Context, modelWarmup *modelv1alpha1.ModelWarmupApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.ModelWarmup, err error) {
	if modelWarmup == nil {
		return nil, fmt.Errorf("modelWarmup provided to Apply must not be nil")
	}
	data, err := json.Marshal(modelWarmup)
	if err != nil {
		return nil, err
	}
	name := modelWarmup.Name
	if name == nil {
		return nil, fmt.Errorf("modelWarmup.Name must be provided to Apply")
	}
	emptyResult := &v1alpha1.ModelWarmup{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(modelwarmupsResource, c.ns, *name, types.ApplyPatchType, data, opts.ToPatchOptions(), "status"), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.ModelWarmup), err
}
