/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "github.com/vllm-project/aibrix/api/model/v1alpha1"
	modelv1alpha1 "github.com/vllm-project/aibrix/pkg/client/applyconfiguration/model/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeModelClaims implements ModelClaimInterface
type FakeModelClaims struct {
	Fake *FakeModelV1alpha1
	ns   string
}

var modelclaimsResource = v1alpha1.SchemeGroupVersion.WithResource("modelclaims")

var modelclaimsKind = v1alpha1.SchemeGroupVersion.WithKind("ModelClaim")

// Get takes name of the modelClaim, and returns the corresponding modelClaim object, and an error if there is any.
func (c *FakeModelClaims) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ModelClaim, err error) {
	emptyResult := &v1alpha1.ModelClaim{}
	obj, err := c.Fake.
		Invokes(testing.NewGetActionWithOptions(modelclaimsResource, c.ns, name, options), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.ModelClaim), err
}

// List takes label and field selectors, and returns the list of ModelClaims that match those selectors.
func (c *FakeModelClaims) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ModelClaimList, err error) {
	emptyResult := &v1alpha1.ModelClaimList{}
	obj, err := c.Fake.
		Invokes(testing.NewListActionWithOptions(modelclaimsResource, modelclaimsKind, c.ns, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ModelClaimList{ListMeta: obj.(*v1alpha1.ModelClaimList).ListMeta}
	for _, item := range obj.(*v1alpha1.ModelClaimList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested modelClaims.
func (c *FakeModelClaims) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchActionWithOptions(modelclaimsResource, c.ns, opts))

}

// Create takes the representation of a modelClaim and creates it.  Returns the server's representation of the modelClaim, and an error, if there is any.
func (c *FakeModelClaims) Create(ctx context.Context, modelClaim *v1alpha1.ModelClaim, opts v1.CreateOptions) (result *v1alpha1.ModelClaim, err error) {
	emptyResult := &v1alpha1.ModelClaim{}
	obj, err := c.Fake.
		Invokes(testing.NewCreateActionWithOptions(modelclaimsResource, c.ns, modelClaim, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.ModelClaim), err
}

// Update takes the representation of a modelClaim and updates it. Returns the server's representation of the modelClaim, and an error, if there is any.
func (c *FakeModelClaims) Update(ctx context.Context, modelClaim *v1alpha1.ModelClaim, opts v1.UpdateOptions) (result *v1alpha1.ModelClaim, err error) {
	emptyResult := &v1alpha1.ModelClaim{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateActionWithOptions(modelclaimsResource, c.ns, modelClaim, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.ModelClaim), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeModelClaims) UpdateStatus(ctx context.Context, modelClaim *v1alpha1.ModelClaim, opts v1.UpdateOptions) (result *v1alpha1.ModelClaim, err error) {
	emptyResult := &v1alpha1.ModelClaim{}
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceActionWithOptions(modelclaimsResource, "status", c.ns, modelClaim, opts), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.ModelClaim), err
}

// Delete takes name of the modelClaim and deletes it. Returns an error if one occurs.
func (c *FakeModelClaims) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(modelclaimsResource, c.ns, name, opts), &v1alpha1.ModelClaim{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeModelClaims) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionActionWithOptions(modelclaimsResource, c.ns, opts, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ModelClaimList{})
	return err
}

// Patch applies the patch and returns the patched modelClaim.
func (c *FakeModelClaims) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ModelClaim, err error) {
	emptyResult := &v1alpha1.ModelClaim{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(modelclaimsResource, c.ns, name, pt, data, opts, subresources...), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.ModelClaim), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied modelClaim.
func (c *FakeModelClaims) Apply(ctx context.Context, modelClaim *modelv1alpha1.ModelClaimApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.ModelClaim, err error) {
	if modelClaim == nil {
		return nil, fmt.Errorf("modelClaim provided to Apply must not be nil")
	}
	data, err := json.Marshal(modelClaim)
	if err != nil {
		return nil, err
	}
	name := modelClaim.Name
	if name == nil {
		return nil, fmt.Errorf("modelClaim.Name must be provided to Apply")
	}
	emptyResult := &v1alpha1.ModelClaim{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(modelclaimsResource, c.ns, *name, types.ApplyPatchType, data, opts.ToPatchOptions()), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.ModelClaim), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeModelClaims) ApplyStatus(ctx context.Context, modelClaim *modelv1alpha1.ModelClaimApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.ModelClaim, err error) {
	if modelClaim == nil {
		return nil, fmt.Errorf("modelClaim provided to Apply must not be nil")
	}
	data, err := json.Marshal(modelClaim)
	if err != nil {
		return nil, err
	}
	name := modelClaim.Name
	if name == nil {
		return nil, fmt.Errorf("modelClaim.Name must be provided to Apply")
	}
	emptyResult := &v1alpha1.ModelClaim{}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceActionWithOptions(modelclaimsResource, c.ns, *name, types.ApplyPatchType, data, opts.ToPatchOptions(), "status"), emptyResult)

	if obj == nil {
		return emptyResult, err
	}
	return obj.(*v1alpha1.ModelClaim), err
}
