apiVersion: v1
kind: Service
metadata:
  name: api-extension
  namespace: system
spec:
  selector:
    app: api-extension
  ports:
    - protocol: TCP
      port: 8100
      targetPort: 8100
  type: ClusterIP