kind: Kustomization

resources:
- ../../templates/deployment
- ../../templates/podautoscaler

patches:
- path: rename_deployment_a40.json
  target:
    kind: Deployment
    name: mock-llama2-7b
- path: rename_podautoscaler_a40.json
  target:
    kind: PodAutoscaler
    name: podautoscaler-mock-llama2-7b
- path: patch_deployment_a40.yaml
  target:
    kind: Deployment
    name: mock-llama2-7b
- path: patch_podautoscaler_a40.yaml
  target:
    kind: PodAutoscaler
    name: podautoscaler-simulator-llama2-7b-a40
    
apiVersion: kustomize.config.k8s.io/v1beta1
