/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vllm-project/aibrix/api/orchestration/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// StormServiceLister helps list StormServices.
// All objects returned here must be treated as read-only.
type StormServiceLister interface {
	// List lists all StormServices in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.StormService, err error)
	// StormServices returns an object that can list and get StormServices.
	StormServices(namespace string) StormServiceNamespaceLister
	StormServiceListerExpansion
}

// stormServiceLister implements the StormServiceLister interface.
type stormServiceLister struct {
	listers.ResourceIndexer[*v1alpha1.StormService]
}

// NewStormServiceLister returns a new StormServiceLister.
func NewStormServiceLister(indexer cache.Indexer) StormServiceLister {
	return &stormServiceLister{listers.New[*v1alpha1.StormService](indexer, v1alpha1.Resource("stormservice"))}
}

// StormServices returns an object that can list and get StormServices.
func (s *stormServiceLister) StormServices(namespace string) StormServiceNamespaceLister {
	return stormServiceNamespaceLister{listers.NewNamespaced[*v1alpha1.StormService](s.ResourceIndexer, namespace)}
}

// StormServiceNamespaceLister helps list and get StormServices.
// All objects returned here must be treated as read-only.
type StormServiceNamespaceLister interface {
	// List lists all StormServices in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.StormService, err error)
	// Get retrieves the StormService from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.StormService, error)
	StormServiceNamespaceListerExpansion
}

// stormServiceNamespaceLister implements the StormServiceNamespaceLister
// interface.
type stormServiceNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.StormService]
}
