apiVersion: model.aibrix.ai/v1alpha1
kind: ModelClaim
metadata:
  name: qwen3-0-6b
  namespace: default
spec:
  modelName: qwen3-0.6b
  podSelector:
    matchLabels:
      pool.aibrix.ai/name: b300-pool-a
  artifactURL: huggingface://Qwen/Qwen3-0.6B
  engine: vllm
  replicas: 1
  engineConfig:
    args:
      --max-model-len: "2048"
---
apiVersion: model.aibrix.ai/v1alpha1
kind: ModelClaim
metadata:
  name: qwen25-0-5b
  namespace: default
spec:
  modelName: qwen2.5-0.5b
  podSelector:
    matchLabels:
      pool.aibrix.ai/name: b300-pool-a
  artifactURL: huggingface://Qwen/Qwen2.5-0.5B-Instruct
  engine: vllm
  replicas: 1
  engineConfig:
    args:
      --max-model-len: "2048"
