{
 "title": "AIBrix Batch",
 "tags": [
  "console",
  "aibrix"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasrc", "query": "opentsdb" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All Errors Overview",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "file_error",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.file.error",
     "tenant": "default",
     "rateDownsampleType": "before_downsample"
    },
    {
     "aggregator": "sum",
     "alias": "job_error",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.job.error",
     "tenant": "default",
     "rateDownsampleType": "before_downsample"
    },
    {
     "aggregator": "sum",
     "alias": "store_error",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.store.error",
     "tenant": "default",
     "rateDownsampleType": "before_downsample"
    },
    {
     "aggregator": "sum",
     "alias": "planner_error",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.planner.error",
     "tenant": "default",
     "rateDownsampleType": "before_downsample"
    }
   ]
  },
  {
   "title": "Latency Avg Overview (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "file_avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.file.duration.ms.avg",
     "tenant": "default"
    },
    {
     "aggregator": "avg",
     "alias": "store_avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.store.duration.ms.avg",
     "tenant": "default"
    },
    {
     "aggregator": "avg",
     "alias": "planner_avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.planner.duration.ms.avg",
     "tenant": "default"
    }
   ]
  },
  {
   "title": "Latency P90 Overview (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "file_p90",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.file.duration.ms.pct90",
     "tenant": "default"
    },
    {
     "aggregator": "avg",
     "alias": "store_p90",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.store.duration.ms.pct90",
     "tenant": "default"
    },
    {
     "aggregator": "avg",
     "alias": "planner_p90",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.planner.duration.ms.pct90",
     "tenant": "default"
    }
   ]
  },
  { "title": "File Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "File Upload Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.file.duration.ms.avg",
     "tenant": "default"
    },
    {
     "aggregator": "avg",
     "alias": "p90",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.file.duration.ms.pct90",
     "tenant": "default"
    },
    {
     "aggregator": "avg",
     "alias": "max",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.file.duration.ms.max",
     "tenant": "default"
    }
   ]
  },
  {
   "title": "File Error Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "error",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.file.error",
     "tenant": "default",
     "rateDownsampleType": "before_downsample"
    }
   ]
  },
  { "title": "Store (Database)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Store Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.store.duration.ms.avg",
     "tenant": "default"
    },
    {
     "aggregator": "avg",
     "alias": "p90",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.store.duration.ms.pct90",
     "tenant": "default"
    },
    {
     "aggregator": "avg",
     "alias": "max",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.store.duration.ms.max",
     "tenant": "default"
    }
   ]
  },
  {
   "title": "Store Error Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "error",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.store.error",
     "tenant": "default",
     "rateDownsampleType": "before_downsample"
    }
   ]
  },
  { "title": "Planner", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Planner Latency (ms)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "avg",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.planner.duration.ms.avg",
     "tenant": "default"
    },
    {
     "aggregator": "avg",
     "alias": "p90",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.planner.duration.ms.pct90",
     "tenant": "default"
    },
    {
     "aggregator": "avg",
     "alias": "max",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.planner.duration.ms.max",
     "tenant": "default"
    }
   ]
  },
  {
   "title": "Planner Error Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "error",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.planner.error",
     "tenant": "default",
     "rateDownsampleType": "before_downsample"
    }
   ]
  },
  {
   "title": "Planner Job Failed Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "job_failed",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.planner.job.failed",
     "tenant": "default",
     "rateDownsampleType": "before_downsample"
    }
   ]
  },
  {
   "title": "Planner Queue Size (Running vs Pending)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "avg",
     "alias": "running",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.planner.queue.running.size",
     "tenant": "default"
    },
    {
     "aggregator": "avg",
     "alias": "pending",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.planner.queue.pending.size",
     "tenant": "default"
    }
   ]
  },
  { "title": "Catalog Resource Views", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Catalog Resources",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "supply",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.planner.catalog.resource.supply",
     "tags": { "resource_type": "gpu|xpu" },
     "tenant": "default"
    },
    {
     "aggregator": "sum",
     "alias": "allocatable",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.planner.catalog.resource.allocatable",
     "tags": { "resource_type": "gpu|xpu" },
     "tenant": "default"
    },
    {
     "aggregator": "sum",
     "alias": "allocated",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.planner.catalog.resource.allocated",
     "tags": { "resource_type": "gpu|xpu" },
     "tenant": "default"
    }
   ]
  },
  {
   "title": "Predicted Catalog Resources",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "supply",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.planner.catalog.prediction.supply",
     "tags": { "resource_type": "gpu|xpu" },
     "tenant": "default"
    },
    {
     "aggregator": "sum",
     "alias": "allocatable",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.planner.catalog.prediction.allocatable",
     "tags": { "resource_type": "gpu|xpu" },
     "tenant": "default"
    },
    {
     "aggregator": "sum",
     "alias": "allocated",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.planner.catalog.prediction.allocated",
     "tags": { "resource_type": "gpu|xpu" },
     "tenant": "default"
    }
   ]
  },
  { "title": "Job", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Job Error & Planner Job Failed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregator": "sum",
     "alias": "job_error",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.job.error",
     "tenant": "default",
     "rateDownsampleType": "before_downsample"
    },
    {
     "aggregator": "sum",
     "alias": "planner_job_failed",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "metric": "aibrix_console.prod.console.planner.job.failed",
     "tenant": "default",
     "rateDownsampleType": "before_downsample"
    }
   ]
  }
 ]
}