resources:
  - ../../../../gateway
  - envoyproxy.yaml

patches:
- path: gateway_patch.yaml


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: busybox
  newName: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/busybox
  newTag: stable
- name: aibrix/plugins
  newName: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/plugins
  newTag: nightly
- name: envoyproxy/envoy
  newName: aibrix-container-registry-cn-beijing.cr.volces.com/envoyproxy/envoy
  newTag: distroless-v1.31.0
- name: aibrix/users
  newName: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/users
  newTag: nightly
- name: redis
  newName: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/redis
  newTag: latest