# Adapted from vLLM
default_install_hook_types:
  - pre-commit
  - commit-msg
default_stages:
  - pre-commit # Run locally
  - manual # Run in CI
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.7
  hooks:
  - id: ruff
    args: [--output-format, github, --fix, --config, &pyproject_toml 'python/aibrix_kvcache/pyproject.toml']
    files: &aibrix_kvcache_files python/aibrix_kvcache/.*
    exclude: &aibrix_py_exclude 'python/aibrix_kvcache/(scripts|tests)/.*|setup.py|common/absl_logging.py'
  - id: ruff-format
    args: [--config, *pyproject_toml]
    files: *aibrix_kvcache_files
    exclude: *aibrix_py_exclude
- repo: https://github.com/codespell-project/codespell
  rev: v2.4.1
  hooks:
  - id: codespell
    additional_dependencies: ['tomli']
    args: ['--toml', *pyproject_toml, '-L', "pris"]
    files: *aibrix_kvcache_files
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v20.1.3
  hooks:
  - id: clang-format
    types_or: [c++, cuda]
    args: [--style=file, --verbose]
    files: *aibrix_kvcache_files
- repo: https://github.com/jackdewinter/pymarkdown
  rev: v0.9.29
  hooks:
  - id: pymarkdown
    exclude: '.*\.inc\.md'
    args: [fix]
    files: *aibrix_kvcache_files
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.11.1
  hooks:
  - id: mypy
    additional_dependencies: [types-redis, pydantic]
    args: [--ignore-missing-imports, --check-untyped-defs, --follow-imports=silent]
    files: *aibrix_kvcache_files
    exclude: *aibrix_py_exclude
- repo: local
  hooks:
  - id: signoff-commit
    name: Sign-off Commit
    entry: bash
    args:
      - -c
      - |
        if ! grep -q "^Signed-off-by: $(git config user.name) <$(git config user.email)>" "$(git rev-parse --git-path COMMIT_EDITMSG)"; then
          printf "\nSigned-off-by: $(git config user.name) <$(git config user.email)>\n" >> "$(git rev-parse --git-path COMMIT_EDITMSG)"
        fi
    language: system
    verbose: true
    stages: [commit-msg]
    files: *aibrix_kvcache_files
  - id: check-aibrix-header
    name: Check AIBrix headers
    entry: python python/aibrix_kvcache/scripts/check_aibrix_header.py
    language: python
    types: [python]
    files: *aibrix_kvcache_files
    exclude: 'python/aibrix_kvcache/setup.py'
  - id: suggestion
    name: Suggestion
    entry: bash -c 'echo "To bypass pre-commit hooks, add --no-verify to git commit."'
    language: system
    verbose: true
    pass_filenames: false
    files: *aibrix_kvcache_files
  # Insert new entries above the `suggestion` entry

