/*
Copyright 2026 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vllm-project/aibrix/api/model/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// ModelClaimLister helps list ModelClaims.
// All objects returned here must be treated as read-only.
type ModelClaimLister interface {
	// List lists all ModelClaims in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ModelClaim, err error)
	// ModelClaims returns an object that can list and get ModelClaims.
	ModelClaims(namespace string) ModelClaimNamespaceLister
	ModelClaimListerExpansion
}

// modelClaimLister implements the ModelClaimLister interface.
type modelClaimLister struct {
	listers.ResourceIndexer[*v1alpha1.ModelClaim]
}

// NewModelClaimLister returns a new ModelClaimLister.
func NewModelClaimLister(indexer cache.Indexer) ModelClaimLister {
	return &modelClaimLister{listers.New[*v1alpha1.ModelClaim](indexer, v1alpha1.Resource("modelclaim"))}
}

// ModelClaims returns an object that can list and get ModelClaims.
func (s *modelClaimLister) ModelClaims(namespace string) ModelClaimNamespaceLister {
	return modelClaimNamespaceLister{listers.NewNamespaced[*v1alpha1.ModelClaim](s.ResourceIndexer, namespace)}
}

// ModelClaimNamespaceLister helps list and get ModelClaims.
// All objects returned here must be treated as read-only.
type ModelClaimNamespaceLister interface {
	// List lists all ModelClaims in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ModelClaim, err error)
	// Get retrieves the ModelClaim from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ModelClaim, error)
	ModelClaimNamespaceListerExpansion
}

// modelClaimNamespaceLister implements the ModelClaimNamespaceLister
// interface.
type modelClaimNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.ModelClaim]
}
