/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vllm-project/aibrix/api/model/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// ModelWarmupLister helps list ModelWarmups.
// All objects returned here must be treated as read-only.
type ModelWarmupLister interface {
	// List lists all ModelWarmups in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ModelWarmup, err error)
	// ModelWarmups returns an object that can list and get ModelWarmups.
	ModelWarmups(namespace string) ModelWarmupNamespaceLister
	ModelWarmupListerExpansion
}

// modelWarmupLister implements the ModelWarmupLister interface.
type modelWarmupLister struct {
	listers.ResourceIndexer[*v1alpha1.ModelWarmup]
}

// NewModelWarmupLister returns a new ModelWarmupLister.
func NewModelWarmupLister(indexer cache.Indexer) ModelWarmupLister {
	return &modelWarmupLister{listers.New[*v1alpha1.ModelWarmup](indexer, v1alpha1.Resource("modelwarmup"))}
}

// ModelWarmups returns an object that can list and get ModelWarmups.
func (s *modelWarmupLister) ModelWarmups(namespace string) ModelWarmupNamespaceLister {
	return modelWarmupNamespaceLister{listers.NewNamespaced[*v1alpha1.ModelWarmup](s.ResourceIndexer, namespace)}
}

// ModelWarmupNamespaceLister helps list and get ModelWarmups.
// All objects returned here must be treated as read-only.
type ModelWarmupNamespaceLister interface {
	// List lists all ModelWarmups in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.ModelWarmup, err error)
	// Get retrieves the ModelWarmup from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.ModelWarmup, error)
	ModelWarmupNamespaceListerExpansion
}

// modelWarmupNamespaceLister implements the ModelWarmupNamespaceLister
// interface.
type modelWarmupNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.ModelWarmup]
}
