apiVersion: v1
kind: ServiceAccount
metadata:
  name: m2
---
apiVersion: v1
kind: Service
metadata:
  name: m2
  labels:
    app: m2
    service: m2
spec:
  ports:
    - name: http
      port: 16000
      targetPort: 16000
  selector:
    app: m2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m2
  labels:
    models.aibrix.com/model-name: m2
    models.aibrix.com/model-port: "16000"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: m2
      version: v1
  template:
    metadata:
      labels:
        app: m2
        version: v1
    spec:
      serviceAccountName: m2
      containers:
        - image: aibrix/vllmm2:v0.1.0
          name: m2
          ports:
            - containerPort: 16000
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace