---
# Source: kuberay-operator/templates/rolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    app.kubernetes.io/name: kuberay-operator
    helm.sh/chart: kuberay-operator-1.2.1
    app.kubernetes.io/instance: aibrix-kuberay-operator
    app.kubernetes.io/managed-by: Helm
  name: aibrix-kuberay-operator
subjects:
- kind: ServiceAccount
  name: kuberay-operator
  namespace: aibrix-system
roleRef:
  kind: ClusterRole
  name: aibrix-kuberay-operator
  apiGroup: rbac.authorization.k8s.io
