apiVersion: model.aibrix.ai/v1alpha1
kind: ModelAdapter
metadata:
  name: lora-1
  namespace: aibrix-system
spec:
  baseModel: llama2-70b
  podSelector:
    matchLabels:
      model.aibrix.ai: llama2-70b
  artifactURL: huggingface://yard1/llama-2-7b-sql-lora-test
  schedulerName: default
