apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen25-7b-qos
  labels:
    model.aibrix.ai/name: qwen25-7b
    model.aibrix.ai/port: "8000"
    model.aibrix.ai/engine: "vllm"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      model.aibrix.ai/name: qwen25-7b
  template:
    metadata:
      labels:
        model.aibrix.ai/name: qwen25-7b
        model.aibrix.ai/port: "8000"
        model.aibrix.ai/engine: "vllm"
    spec:
      initContainers:
        - command:
            - aibrix_download
            - --model-uri
            - tos://aibrix-artifact-testing/models/llama-3.1-8b-instruct/
            - --local-dir
            - /models/
          env:
            - name: DOWNLOADER_NUM_THREADS
              value: "16"
            - name: DOWNLOADER_ALLOW_FILE_SUFFIX
              value: json, safetensors
            - name: TOS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: TOS_ACCESS_KEY
                  name: tos-credential
            - name: TOS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: TOS_SECRET_KEY
                  name: tos-credential
            - name: TOS_ENDPOINT
              value: https://tos-s3-cn-beijing.ivolces.com
            - name: TOS_REGION
              value: cn-beijing
          image: aibrix-cn-beijing.cr.volces.com/aibrix/runtime:v0.3.0
          name: init-model
          volumeMounts:
            - mountPath: /models
              name: model-hostpath
      containers:
        - name: vllm-openai
          image:  aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/vllm/vllm-openai:v0.9.2 #docker.1ms.run/aibrix/vllm-openai:v0.6.2-distributed
          imagePullPolicy: Always
          command:
            - python3
            - -m
            - vllm.entrypoints.openai.api_server
            - --port
            - "8000"
            - --uvicorn-log-level
            - warning
            - --model
            - /models/llama-3.1-8b-instruct/
            - --served-model-name
            - qwen25-7b
            - --max-model-len
            - "32000" # please modify this field if your gpu has more room
            - --enable-prefix-caching
            - --disable-fastapi-docs
            - --trust-remote-code
            - --disable-log-requests
            - --swap-space
            - "0"
          env:
            - name: VLLM_RPC_TIMEOUT
              value: "1000000"
            - name: VLLM_IMAGE_FETCH_TIMEOUT
              value: "600"
            - name: VLLM_VIDEO_FETCH_TIMEOUT
              value: "1200"
            - name: VLLM_AUDIO_FETCH_TIMEOUT
              value: "1200"
          volumeMounts:
            - mountPath: /models
              name: model-hostpath
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "10"
              # memory: "150G"
            requests:
              nvidia.com/gpu: "1"
              cpu: "10"
              # memory: "150G"
      volumes:
        - name: model-hostpath
          hostPath:
            path: /data/Qwen
            type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  labels:
    model.aibrix.ai/name: qwen25-7b
    model.aibrix.ai/port: "8000"
    model.aibrix.ai/engine: "vllm"
    prometheus-discovery: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
  name: qwen25-7b # Note: The Service name must match the label value `model.aibrix.ai/name` in the Deployment
  namespace: default
spec:
  ports:
    - name: serve
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    model.aibrix.ai/name: qwen25-7b
  type: ClusterIP
