apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen-audio-7b
  labels:
    model.aibrix.ai/name: qwen-audio-7b
    model.aibrix.ai/port: "8000"
    model.aibrix.ai/engine: "vllm"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      model.aibrix.ai/name: qwen-audio-7b
  template:
    metadata:
      labels:
        model.aibrix.ai/name: qwen-audio-7b
        model.aibrix.ai/port: "8000"
        model.aibrix.ai/engine: "vllm"
    spec:
      initContainers:
        - command:
            - aibrix_download
            - --model-uri
            - tos://aibrix-artifact-testing/models/Qwen2-Audio-7B-Instruct/
            - --local-dir
            - /models/
          env:
            - name: DOWNLOADER_NUM_THREADS
              value: "16"
            - name: TOS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  key: TOS_ACCESS_KEY
                  name: tos-credential
            - name: TOS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: TOS_SECRET_KEY
                  name: tos-credential
            - name: TOS_ENDPOINT
              value: https://tos-s3-cn-beijing.ivolces.com
            - name: TOS_REGION
              value: cn-beijing
          image: aibrix-cn-beijing.cr.volces.com/aibrix/runtime:v0.3.0
          name: init-model
          volumeMounts:
            - mountPath: /models
              name: model-hostpath
      containers:
        - name: vllm-openai
          image: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/vllm/vllm-openai:v0.9.2
          imagePullPolicy: Always
          command:
            - sh
            - -c
            - |
              python3 -m pip install --no-cache-dir "vllm[audio]" && \
              python3 -m vllm.entrypoints.openai.api_server \
                --port 8000 \
                --uvicorn-log-level warning \
                --model /models/Qwen2-Audio-7B-Instruct/ \
                --served-model-name qwen-audio-7b \
                --enable-prefix-caching \
                --disable-fastapi-docs \
                --trust-remote-code \
                --no-enable-chunked-prefill \
                --disable-log-requests \
                --swap-space 0
          env:
            - name: VLLM_RPC_TIMEOUT
              value: "1000000"
            - name: VLLM_IMAGE_FETCH_TIMEOUT
              value: "600"
            - name: VLLM_VIDEO_FETCH_TIMEOUT
              value: "1200"
            - name: VLLM_AUDIO_FETCH_TIMEOUT
              value: "1200"
          volumeMounts:
            - mountPath: /models
              name: model-hostpath
          resources:
            limits:
              nvidia.com/gpu: "1"
              cpu: "10"
            requests:
              nvidia.com/gpu: "1"
              cpu: "10"
      volumes:
        - name: model-hostpath
          hostPath:
            path: /root/models
            type: DirectoryOrCreate

---

apiVersion: v1
kind: Service
metadata:
  labels:
    model.aibrix.ai/name: qwen-audio-7b
    model.aibrix.ai/port: "8000"
    model.aibrix.ai/engine: "vllm"
    prometheus-discovery: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
  name: qwen-audio-7b 
  namespace: default
spec:
  ports:
    - name: serve
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    model.aibrix.ai/name: qwen-audio-7b
  type: ClusterIP
