name: Test Helm Chart

on:
  pull_request:
    paths:
      - 'dist/chart/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0
      
      - uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.x'
          check-latest: true
      
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (lint)
        working-directory: ./dist/chart
        run: ct lint
      
      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Install dependencies # TODO: use main dependency and not release one
        run: |
          kubectl create -f https://github.com/vllm-project/aibrix/releases/download/v0.3.0/aibrix-dependency-v0.3.0.yaml
      
      - name: Chart test
        working-directory: ./dist/chart
        run: |
          kubectl create namespace aibrix-system
          ct install --chart-dirs . --charts . --namespace aibrix-system