name: Test Helm Chart

on:
  pull_request:
    paths:
      - 'dist/chart/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      
      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.17.0
      
      - uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.x'
          check-latest: true
      
      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (lint)
        run: helm lint ./dist/chart
      
      - name: Create kind cluster
        uses: helm/kind-action@v1.12.0

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Install Envoy Gateway
        run: |
          helm install eg oci://docker.io/envoyproxy/gateway-helm --version v0.0.0-latest -n envoy-gateway-system --create-namespace --wait
      
      - name: Install Kuberay operator
        run: |
          helm install kuberay-operator kuberay/kuberay-operator \
          --namespace kuberay-system  \ 
          --version 1.2.1 \
          --set env[0].name=ENABLE_PROBES_INJECTION \
          --set-string env[0].value=false \
          --set fullnameOverride=kuberay-operator \
          --set featureGates[0].name=RayClusterStatusConditions \
          --set featureGates[0].enabled=true \
          --create-namespace \
          --wait

      - name: Install Aibrix CRDs
        run: |
          kubectl apply -f dist/chart/crds
      
      - name: Chart test
        working-directory: ./dist/chart
        run: |
          kubectl create namespace aibrix-system
          ct install --chart-dirs . --charts . --namespace aibrix-system