name: Docker Push Images

on:
  push:
    branches: [ "main", "release-*"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Login to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Container Images
        run: |
          make docker-build
          make docker-build-plugins
          make docker-build-runtime
          make docker-build-users

      - name: Push Container Images to DockerHub
        run: |
          make docker-push
          make docker-push-plugins
          make docker-push-runtime
          make docker-push-users

      - name: Build Container Images with Github Container Registry prefix
        run: |
          IMG=ghcr.io/aibrix/controller-manager:${{ github.sha }} make docker-build
          PLUGINS_IMG=ghcr.io/aibrix/plugins:${{ github.sha }} make docker-build-plugins
          RUNTIME_IMG=ghcr.io/aibrix/runtime:${{ github.sha }} make docker-build-runtime
          USERS_IMG=ghcr.io/aibrix/users:${{ github.sha }} make docker-build-users

      - name: Push Container Images to Github Container Registry
        run: |
          IMG=ghcr.io/aibrix/controller-manager:${{ github.sha }} AIBRIX_CONTAINER_REGISTRY_NAMESPACE=ghcr.io/aibrix make docker-push
          PLUGINS_IMG=ghcr.io/aibrix/plugins:${{ github.sha }} AIBRIX_CONTAINER_REGISTRY_NAMESPACE=ghcr.io/aibrix make docker-push-plugins
          RUNTIME_IMG=ghcr.io/aibrix/runtime:${{ github.sha }} AIBRIX_CONTAINER_REGISTRY_NAMESPACE=ghcr.io/aibrix make docker-push-runtime
          USERS_IMG=ghcr.io/aibrix/users:${{ github.sha }} AIBRIX_CONTAINER_REGISTRY_NAMESPACE=ghcr.io/aibrix make docker-push-users
