name: Docker Build Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker Build - Controller Manager
      run: make docker-build
    - name: Docker Build - Gateway Plugins
      run: make docker-build-plugins
    - name: Docker Build - Runtime
      run: make docker-build-runtime
