name: Docker Push Images

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    branches: [ "main", "release-*" ]

jobs:
  build-push-dockerhub:
    if: github.repository == 'vllm-project/aibrix'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        component:
          - name: controller-manager
            file: build/container/Dockerfile
          - name: gateway-plugins
            file: build/container/Dockerfile.gateway
          - name: metadata-service
            file: build/container/Dockerfile.metadata
          - name: runtime
            file: build/container/Dockerfile.runtime
          - name: kvcache-watcher
            file: build/container/Dockerfile.kvcache
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build and push ${{ matrix.component.name }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          file: ${{ matrix.component.file }}
          push: true
          tags: |
            aibrix/${{ matrix.component.name }}:${{ github.sha }}
            aibrix/${{ matrix.component.name }}:nightly

  build-push-ghcr:
    if: github.repository == 'vllm-project/aibrix'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      matrix:
        component:
          - name: controller-manager
            file: build/container/Dockerfile
          - name: gateway-plugins
            file: build/container/Dockerfile.gateway
          - name: metadata-service
            file: build/container/Dockerfile.metadata
          - name: runtime
            file: build/container/Dockerfile.runtime
          - name: kvcache-watcher
            file: build/container/Dockerfile.kvcache
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Login to Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.AIBRIX_ORG_PACKAGE_UPDATE_GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build and push ${{ matrix.component.name }}
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          file: ${{ matrix.component.file }}
          push: true
          tags: |
            ghcr.io/aibrix/${{ matrix.component.name }}:${{ github.sha }}
            ghcr.io/aibrix/${{ matrix.component.name }}:nightly
