name: Docker Push Images

on:
  push:
    branches: [ "main", "release-*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # build container images
      - name: Docker Build - Controller Manager
        run: make docker-build
      - name: Docker Build - Gateway Plugins
        run: make docker-build-plugins
      - name: Docker Build - Runtime
        run: make docker-build-runtime
      - name: Docker Build - Users
        run: make docker-build-users
      # push container image to dockerhub
      - name: Push Image - Controller Manager
        run: make docker-push
      - name: Push Image - Gateway Plugins
        run: make docker-push-plugins
      - name: Push Image - Runtime
        run: make docker-push-runtime
      - name: Push Image - Users
        run: make docker-push-users
