name: Docker Push Images

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    branches: [ "main", "release-*" ]

jobs:
  build-push-dockerhub:
    if: github.repository == 'vllm-project/aibrix'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build and push controller-manager
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          file: build/container/Dockerfile
          push: true
          tags: |
            aibrix/controller-manager:${{ github.sha }}
            aibrix/controller-manager:nightly
      - name: Build and push gateway-plugins
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          file: build/container/Dockerfile.gateway
          push: true
          tags: |
            aibrix/gateway-plugins:${{ github.sha }}
            aibrix/gateway-plugins:nightly
      - name: Build and push metadata-service
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          file: build/container/Dockerfile.metadata
          push: true
          tags: |
            aibrix/metadata-service:${{ github.sha }}
            aibrix/metadata-service:nightly
      - name: Build and push runtime
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          file: build/container/Dockerfile.runtime
          push: true
          tags: |
            aibrix/runtime:${{ github.sha }}
            aibrix/runtime:nightly
      - name: Build and push kvcache-watcher
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          file: build/container/Dockerfile.kvcache
          push: true
          tags: |
            aibrix/kvcache-watcher:${{ github.sha }}
            aibrix/kvcache-watcher:nightly

  build-push-ghcr:
    if: github.repository == 'vllm-project/aibrix'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Login to Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.AIBRIX_ORG_PACKAGE_UPDATE_GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Build and push controller-manager
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          file: build/container/Dockerfile
          push: true
          tags: |
            ghcr.io/aibrix/controller-manager:${{ github.sha }}
            ghcr.io/aibrix/controller-manager:nightly
      - name: Build and push gateway-plugins
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          file: build/container/Dockerfile.gateway
          push: true
          tags: |
            ghcr.io/aibrix/gateway-plugins:${{ github.sha }}
            ghcr.io/aibrix/gateway-plugins:nightly
      - name: Build and push metadata-service
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          file: build/container/Dockerfile.metadata
          push: true
          tags: |
            ghcr.io/aibrix/metadata-service:${{ github.sha }}
            ghcr.io/aibrix/metadata-service:nightly
      - name: Build and push runtime
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          file: build/container/Dockerfile.runtime
          push: true
          tags: |
            ghcr.io/aibrix/runtime:${{ github.sha }}
            ghcr.io/aibrix/runtime:nightly
      - name: Build and push kvcache-watcher
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          file: build/container/Dockerfile.kvcache
          push: true
          tags: |
            ghcr.io/aibrix/kvcache-watcher:${{ github.sha }}
            ghcr.io/aibrix/kvcache-watcher:nightly
