/*
Copyright 2024 The Aibrix Team.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/vllm-project/aibrix/api/orchestration/v1alpha1"
	orchestrationv1alpha1 "github.com/vllm-project/aibrix/pkg/client/applyconfiguration/orchestration/v1alpha1"
	typedorchestrationv1alpha1 "github.com/vllm-project/aibrix/pkg/client/clientset/versioned/typed/orchestration/v1alpha1"
	gentype "k8s.io/client-go/gentype"
)

// fakeRayClusterReplicaSets implements RayClusterReplicaSetInterface
type fakeRayClusterReplicaSets struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.RayClusterReplicaSet, *v1alpha1.RayClusterReplicaSetList, *orchestrationv1alpha1.RayClusterReplicaSetApplyConfiguration]
	Fake *FakeOrchestrationV1alpha1
}

func newFakeRayClusterReplicaSets(fake *FakeOrchestrationV1alpha1, namespace string) typedorchestrationv1alpha1.RayClusterReplicaSetInterface {
	return &fakeRayClusterReplicaSets{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.RayClusterReplicaSet, *v1alpha1.RayClusterReplicaSetList, *orchestrationv1alpha1.RayClusterReplicaSetApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("rayclusterreplicasets"),
			v1alpha1.SchemeGroupVersion.WithKind("RayClusterReplicaSet"),
			func() *v1alpha1.RayClusterReplicaSet { return &v1alpha1.RayClusterReplicaSet{} },
			func() *v1alpha1.RayClusterReplicaSetList { return &v1alpha1.RayClusterReplicaSetList{} },
			func(dst, src *v1alpha1.RayClusterReplicaSetList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.RayClusterReplicaSetList) []*v1alpha1.RayClusterReplicaSet {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.RayClusterReplicaSetList, items []*v1alpha1.RayClusterReplicaSet) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
